/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Apr 07 14:19:40 GMT 2025
 */

package sqlancer.tidb;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class TiDBOracleFactory_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "sqlancer.tidb.TiDBOracleFactory"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\yewjo\\OneDrive\\Desktop\\NUS\\y4s2\\cs3213\\project\\sqlancer"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\yewjo\\AppData\\Local\\Temp\\"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(TiDBOracleFactory_ESTest_scaffolding.class.getClassLoader() ,
      "sqlancer.common.oracle.CERTOracle",
      "sqlancer.tidb.TiDBOracleFactory",
      "sqlancer.AbstractAction",
      "sqlancer.OracleFactory",
      "sqlancer.StatementExecutor",
      "sqlancer.tidb.oracle.TiDBTLPHavingOracle",
      "sqlancer.SQLProviderAdapter",
      "sqlancer.common.gen.ExpressionGenerator",
      "sqlancer.tidb.TiDBBugs",
      "sqlancer.Main$StateLogger",
      "sqlancer.common.oracle.CompositeTestOracle",
      "sqlancer.common.query.ExpectedErrors",
      "sqlancer.GlobalState",
      "sqlancer.tidb.TiDBProvider$Action",
      "sqlancer.common.ast.newast.Select",
      "sqlancer.common.gen.UntypedExpressionGenerator",
      "sqlancer.tidb.TiDBProvider",
      "sqlancer.common.schema.AbstractSchema",
      "sqlancer.common.query.ExpectedErrors$ExpectedErrorsBuilder",
      "sqlancer.Main",
      "sqlancer.tidb.ast.TiDBExpression",
      "sqlancer.DatabaseProvider",
      "sqlancer.common.gen.PartitionGenerator",
      "sqlancer.tidb.TiDBProvider$TiDBGlobalState",
      "sqlancer.Main$QueryManager",
      "sqlancer.ProviderAdapter",
      "sqlancer.common.query.Query",
      "sqlancer.common.oracle.CERTOracle$CheckedFunction",
      "sqlancer.common.oracle.TLPWhereOracle",
      "sqlancer.SQLancerDBConnection",
      "sqlancer.MainOptions",
      "sqlancer.Randomly",
      "sqlancer.tidb.TiDBErrors",
      "sqlancer.common.oracle.TestOracle",
      "sqlancer.common.gen.TLPWhereGenerator",
      "sqlancer.common.query.SQLancerResultSet",
      "sqlancer.common.gen.CERTGenerator",
      "sqlancer.common.ast.newast.Expression",
      "sqlancer.SQLGlobalState",
      "sqlancer.StateToReproduce",
      "sqlancer.tidb.TiDBSchema",
      "sqlancer.DBMSSpecificOptions",
      "sqlancer.tidb.TiDBExpressionGenerator",
      "sqlancer.tidb.TiDBOracleFactory$2",
      "sqlancer.tidb.TiDBOracleFactory$1",
      "sqlancer.common.log.Loggable",
      "sqlancer.IgnoreMeException",
      "sqlancer.tidb.oracle.TiDBTLPBase",
      "sqlancer.tidb.TiDBOracleFactory$4",
      "sqlancer.tidb.TiDBOracleFactory$3",
      "sqlancer.tidb.TiDBOracleFactory$5",
      "sqlancer.tidb.oracle.TiDBDQPOracle",
      "sqlancer.Reproducer",
      "sqlancer.common.oracle.TernaryLogicPartitioningOracleBase"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(TiDBOracleFactory_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "sqlancer.tidb.TiDBOracleFactory",
      "sqlancer.GlobalState",
      "sqlancer.SQLGlobalState",
      "sqlancer.tidb.TiDBProvider$TiDBGlobalState",
      "sqlancer.common.query.Query",
      "sqlancer.common.query.SQLQueryAdapter",
      "sqlancer.common.query.ExpectedErrors",
      "sqlancer.common.query.SQLQueryResultCheckAdapter",
      "sqlancer.tidb.oracle.TiDBDQPOracle",
      "sqlancer.tidb.TiDBErrors",
      "sqlancer.tidb.TiDBBugs",
      "sqlancer.common.gen.UntypedExpressionGenerator",
      "sqlancer.tidb.TiDBExpressionGenerator",
      "sqlancer.common.query.ExpectedErrors$ExpectedErrorsBuilder",
      "sqlancer.common.oracle.TLPWhereOracle",
      "sqlancer.common.oracle.CERTOracle",
      "sqlancer.common.oracle.TernaryLogicPartitioningOracleBase",
      "sqlancer.tidb.oracle.TiDBTLPBase",
      "sqlancer.tidb.oracle.TiDBTLPHavingOracle",
      "sqlancer.common.oracle.CompositeTestOracle",
      "sqlancer.ExpandedGlobalState",
      "sqlancer.materialize.MaterializeGlobalState"
    );
  }
}
