/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 07 13:10:12 GMT 2025
 */

package sqlancer.evosuite.cnosdb.oracle.tlp;

import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.fail;

import java.util.LinkedList;
import java.util.List;

import org.junit.jupiter.api.Test;

import sqlancer.Randomly;
import sqlancer.cnosdb.CnosDBGlobalState;
import sqlancer.cnosdb.CnosDBSchema;
import sqlancer.cnosdb.ast.CnosDBExpression;
import sqlancer.cnosdb.ast.CnosDBJoin;
import sqlancer.cnosdb.oracle.tlp.CnosDBTLPBase;
import sqlancer.common.gen.ExpressionGenerator;

public class CnosDBTLPBase_ESTest {

    @Test
    public void test0() throws Throwable {
        CnosDBTLPBase cnosDBTLPBase0 = new CnosDBTLPBase((CnosDBGlobalState) null);
        LinkedList<CnosDBSchema.CnosDBColumn> linkedList0 = new LinkedList<CnosDBSchema.CnosDBColumn>();
        CnosDBSchema.CnosDBTable[] cnosDBSchema_CnosDBTableArray0 = new CnosDBSchema.CnosDBTable[7];
        List<CnosDBSchema.CnosDBTable> list0 = Randomly.subset(cnosDBSchema_CnosDBTableArray0);
        // Undeclared exception!
        try {
            cnosDBTLPBase0.getJoinStatements(linkedList0, list0);
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("sqlancer.cnosdb.gen.CnosDBExpressionGenerator", e);
        }
    }

    private void verifyException(String s, NullPointerException e) {
    }

    @Test
    public void test1() throws Throwable {
        CnosDBGlobalState cnosDBGlobalState0 = new CnosDBGlobalState();
        // Undeclared exception!
        try {
            CnosDBTLPBase.createSubquery(cnosDBGlobalState0, "svxjp.W+DgIOShdTSs", (CnosDBSchema.CnosDBTables) null);
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("sqlancer.cnosdb.gen.CnosDBExpressionGenerator", e);
        }
    }

    @Test
    public void test2() throws Throwable {
        CnosDBGlobalState cnosDBGlobalState0 = new CnosDBGlobalState();
        CnosDBTLPBase cnosDBTLPBase0 = new CnosDBTLPBase(cnosDBGlobalState0);
        // Undeclared exception!
        try {
            cnosDBTLPBase0.check();
            fail("Expecting exception: AssertionError");

        } catch (AssertionError e) {
            //
            // null
            //
        }
    }

    // @Test
    // public void test3() throws Throwable {
    // CnosDBGlobalState cnosDBGlobalState0 = new CnosDBGlobalState();
    // CnosDBTLPBase cnosDBTLPBase0 = new CnosDBTLPBase(cnosDBGlobalState0);
    // LinkedList<CnosDBSchema.CnosDBTable> linkedList0 = new LinkedList<CnosDBSchema.CnosDBTable>();
    // CnosDBSchema.CnosDBTables cnosDBSchema_CnosDBTables0 = new CnosDBSchema.CnosDBTables(linkedList0);
    // cnosDBTLPBase0.targetTables = cnosDBSchema_CnosDBTables0;
    // List<CnosDBExpression> list0 = cnosDBTLPBase0.generateFetchColumns();
    // assertTrue(list0.isEmpty());
    // }

    @Test
    public void test4() throws Throwable {
        CnosDBGlobalState cnosDBGlobalState0 = new CnosDBGlobalState();
        CnosDBTLPBase cnosDBTLPBase0 = new CnosDBTLPBase(cnosDBGlobalState0);
        // Undeclared exception!
        try {
            cnosDBTLPBase0.generateFetchColumns();
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // java.util.List.of(Ljava/lang/Object;)Ljava/util/List;
            //
            verifyException("sqlancer.cnosdb.oracle.tlp.CnosDBTLPBase", e);
        }
    }

    @Test
    public void test5() throws Throwable {
        CnosDBGlobalState cnosDBGlobalState0 = new CnosDBGlobalState();
        CnosDBTLPBase cnosDBTLPBase0 = new CnosDBTLPBase(cnosDBGlobalState0);
        // Undeclared exception!
        try {
            cnosDBTLPBase0.generateFetchColumns();
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("sqlancer.cnosdb.oracle.tlp.CnosDBTLPBase", e);
        }
    }

    @Test
    public void test6() throws Throwable {
        CnosDBTLPBase cnosDBTLPBase0 = new CnosDBTLPBase((CnosDBGlobalState) null);
        try {
            cnosDBTLPBase0.check();
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("sqlancer.cnosdb.oracle.tlp.CnosDBTLPBase", e);
        }
    }

    @Test
    public void test7() throws Throwable {
        CnosDBGlobalState cnosDBGlobalState0 = new CnosDBGlobalState();
        CnosDBTLPBase cnosDBTLPBase0 = new CnosDBTLPBase(cnosDBGlobalState0);
        ExpressionGenerator<CnosDBExpression> expressionGenerator0 = cnosDBTLPBase0.getGen();
        assertNull(expressionGenerator0);
    }

    @Test
    public void test8() throws Throwable {
        CnosDBGlobalState cnosDBGlobalState0 = new CnosDBGlobalState();
        CnosDBTLPBase cnosDBTLPBase0 = new CnosDBTLPBase(cnosDBGlobalState0);
        LinkedList<CnosDBSchema.CnosDBTable> linkedList0 = new LinkedList<CnosDBSchema.CnosDBTable>();
        LinkedList<CnosDBJoin> linkedList1 = new LinkedList<CnosDBJoin>();
        // Undeclared exception!
        try {
            cnosDBTLPBase0.generateSelectBase(linkedList0, linkedList1);
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("sqlancer.cnosdb.gen.CnosDBExpressionGenerator", e);
        }
    }
}
