/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Apr 07 13:02:33 GMT 2025
 */

package sqlancer.yugabyte.ysql.ast;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class YSQLColumnValue_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "sqlancer.yugabyte.ysql.ast.YSQLColumnValue"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\yewjo\\OneDrive\\Desktop\\NUS\\y4s2\\cs3213\\project\\sqlancer"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\yewjo\\AppData\\Local\\Temp\\"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(YSQLColumnValue_ESTest_scaffolding.class.getClassLoader() ,
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$BitConstant",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$RangeConstant",
      "sqlancer.yugabyte.ysql.ast.YSQLExpression",
      "sqlancer.yugabyte.ysql.YSQLSchema",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$InetConstant",
      "sqlancer.common.schema.AbstractSchema",
      "sqlancer.yugabyte.ysql.ast.YSQLColumnValue",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$YSQLConstantBase",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$BooleanConstant",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$DecimalConstant",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$StringConstant",
      "sqlancer.yugabyte.ysql.YSQLSchema$YSQLDataType",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$FloatConstant",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$IntConstant",
      "sqlancer.common.schema.AbstractTableColumn",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$DoubleConstant",
      "sqlancer.IgnoreMeException",
      "sqlancer.common.ast.newast.Expression",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$ByteConstant",
      "sqlancer.yugabyte.ysql.YSQLSchema$YSQLColumn",
      "sqlancer.common.schema.AbstractTable",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$YSQLNullConstant"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(YSQLColumnValue_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "sqlancer.yugabyte.ysql.ast.YSQLColumnValue",
      "sqlancer.common.schema.AbstractTableColumn",
      "sqlancer.yugabyte.ysql.YSQLSchema$YSQLColumn",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$IntConstant",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$StringConstant",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$YSQLConstantBase",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$DoubleConstant",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$RangeConstant",
      "sqlancer.SQLConstantUtils",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$ByteConstant",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$BooleanConstant",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$DecimalConstant",
      "sqlancer.common.schema.AbstractTable",
      "sqlancer.common.schema.AbstractRelationalTable",
      "sqlancer.yugabyte.ysql.YSQLSchema$YSQLTable",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$YSQLNullConstant",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$FloatConstant",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$InetConstant",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$BitConstant",
      "sqlancer.IgnoreMeException",
      "sqlancer.ProviderAdapter",
      "sqlancer.SQLProviderAdapter",
      "sqlancer.ExpandedProvider",
      "sqlancer.Randomly$StringGenerationStrategy$4",
      "sqlancer.Randomly$StringGenerationStrategy",
      "sqlancer.Randomly"
    );
  }
}
