/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 07 13:55:28 GMT 2025
 */

package sqlancer.yugabyte.ysql.ast;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sqlancer.yugabyte.ysql.YSQLSchema;
import sqlancer.yugabyte.ysql.ast.YSQLBinaryBitOperation;
import sqlancer.yugabyte.ysql.ast.YSQLConstant;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class YSQLBinaryBitOperation_ESTest extends YSQLBinaryBitOperation_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      YSQLBinaryBitOperation.YSQLBinaryBitOperator ySQLBinaryBitOperation_YSQLBinaryBitOperator0 = YSQLBinaryBitOperation.YSQLBinaryBitOperator.getRandom();
      String string0 = ySQLBinaryBitOperation_YSQLBinaryBitOperator0.getTextRepresentation();
      assertEquals("||", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      YSQLBinaryBitOperation.YSQLBinaryBitOperator ySQLBinaryBitOperation_YSQLBinaryBitOperator0 = YSQLBinaryBitOperation.YSQLBinaryBitOperator.BITWISE_AND;
      YSQLConstant.YSQLNullConstant ySQLConstant_YSQLNullConstant0 = new YSQLConstant.YSQLNullConstant();
      YSQLBinaryBitOperation ySQLBinaryBitOperation0 = new YSQLBinaryBitOperation(ySQLBinaryBitOperation_YSQLBinaryBitOperator0, ySQLConstant_YSQLNullConstant0, ySQLConstant_YSQLNullConstant0);
      YSQLSchema.YSQLDataType ySQLSchema_YSQLDataType0 = ySQLBinaryBitOperation0.getExpressionType();
      assertEquals(YSQLSchema.YSQLDataType.BIT, ySQLSchema_YSQLDataType0);
  }
}
