/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 07 13:04:21 GMT 2025
 */

package sqlancer.yugabyte.ysql.ast;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sqlancer.yugabyte.ysql.ast.YSQLConstant;
import sqlancer.yugabyte.ysql.ast.YSQLExpression;
import sqlancer.yugabyte.ysql.ast.YSQLOrderByTerm;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class YSQLOrderByTerm_ESTest extends YSQLOrderByTerm_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      YSQLOrderByTerm.YSQLOrder ySQLOrderByTerm_YSQLOrder0 = YSQLOrderByTerm.YSQLOrder.ASC;
      YSQLOrderByTerm ySQLOrderByTerm0 = new YSQLOrderByTerm((YSQLExpression) null, ySQLOrderByTerm_YSQLOrder0);
      YSQLOrderByTerm.YSQLOrder ySQLOrderByTerm_YSQLOrder1 = ySQLOrderByTerm0.getOrder();
      assertSame(ySQLOrderByTerm_YSQLOrder0, ySQLOrderByTerm_YSQLOrder1);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      YSQLOrderByTerm.YSQLOrder ySQLOrderByTerm_YSQLOrder0 = YSQLOrderByTerm.YSQLOrder.ASC;
      YSQLOrderByTerm ySQLOrderByTerm0 = new YSQLOrderByTerm((YSQLExpression) null, ySQLOrderByTerm_YSQLOrder0);
      YSQLExpression ySQLExpression0 = ySQLOrderByTerm0.getExpr();
      assertNull(ySQLExpression0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      YSQLOrderByTerm.YSQLOrder ySQLOrderByTerm_YSQLOrder0 = YSQLOrderByTerm.YSQLOrder.getRandomOrder();
      assertEquals(YSQLOrderByTerm.YSQLOrder.ASC, ySQLOrderByTerm_YSQLOrder0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      YSQLConstant.YSQLNullConstant ySQLConstant_YSQLNullConstant0 = new YSQLConstant.YSQLNullConstant();
      YSQLOrderByTerm.YSQLOrder ySQLOrderByTerm_YSQLOrder0 = YSQLOrderByTerm.YSQLOrder.ASC;
      YSQLOrderByTerm ySQLOrderByTerm0 = new YSQLOrderByTerm(ySQLConstant_YSQLNullConstant0, ySQLOrderByTerm_YSQLOrder0);
      // Undeclared exception!
      try { 
        ySQLOrderByTerm0.getExpectedValue();
        fail("Expecting exception: AssertionError");
      
      } catch(AssertionError e) {
         //
         // sqlancer.yugabyte.ysql.ast.YSQLOrderByTerm@2
         //
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      YSQLConstant ySQLConstant0 = YSQLConstant.createNullConstant();
      YSQLOrderByTerm.YSQLOrder ySQLOrderByTerm_YSQLOrder0 = YSQLOrderByTerm.YSQLOrder.ASC;
      YSQLOrderByTerm ySQLOrderByTerm0 = new YSQLOrderByTerm(ySQLConstant0, ySQLOrderByTerm_YSQLOrder0);
      ySQLOrderByTerm0.getExpressionType();
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      YSQLConstant.YSQLNullConstant ySQLConstant_YSQLNullConstant0 = new YSQLConstant.YSQLNullConstant();
      YSQLOrderByTerm ySQLOrderByTerm0 = new YSQLOrderByTerm(ySQLConstant_YSQLNullConstant0, (YSQLOrderByTerm.YSQLOrder) null);
      ySQLOrderByTerm0.getOrder();
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      YSQLConstant ySQLConstant0 = YSQLConstant.createNullConstant();
      YSQLOrderByTerm.YSQLOrder ySQLOrderByTerm_YSQLOrder0 = YSQLOrderByTerm.YSQLOrder.DESC;
      YSQLOrderByTerm ySQLOrderByTerm0 = new YSQLOrderByTerm(ySQLConstant0, ySQLOrderByTerm_YSQLOrder0);
      YSQLExpression ySQLExpression0 = ySQLOrderByTerm0.getExpr();
      assertSame(ySQLConstant0, ySQLExpression0);
  }
}
