/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Apr 07 13:55:28 GMT 2025
 */

package sqlancer.yugabyte.ysql.ast;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class YSQLBinaryBitOperation_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "sqlancer.yugabyte.ysql.ast.YSQLBinaryBitOperation"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\yewjo\\OneDrive\\Desktop\\NUS\\y4s2\\cs3213\\project\\sqlancer"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\yewjo\\AppData\\Local\\Temp\\"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(YSQLBinaryBitOperation_ESTest_scaffolding.class.getClassLoader() ,
      "sqlancer.yugabyte.ysql.ast.YSQLConstant",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$RangeConstant",
      "sqlancer.yugabyte.ysql.YSQLSchema",
      "sqlancer.Randomly",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$YSQLConstantBase",
      "sqlancer.common.ast.BinaryNode",
      "sqlancer.common.ast.BinaryOperatorNode",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$BooleanConstant",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$DecimalConstant",
      "sqlancer.common.visitor.BinaryOperation",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$StringConstant",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$FloatConstant",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$IntConstant",
      "sqlancer.common.schema.AbstractTableColumn",
      "sqlancer.Randomly$StringGenerationStrategy",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$DoubleConstant",
      "sqlancer.common.ast.newast.Expression",
      "sqlancer.common.ast.BinaryOperatorNode$Operator",
      "sqlancer.Randomly$StringGenerationStrategy$4",
      "sqlancer.Randomly$StringGenerationStrategy$3",
      "sqlancer.Randomly$StringGenerationStrategy$2",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$YSQLNullConstant",
      "sqlancer.Randomly$StringGenerationStrategy$1",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$BitConstant",
      "sqlancer.yugabyte.ysql.ast.YSQLExpression",
      "sqlancer.yugabyte.ysql.ast.YSQLBinaryBitOperation",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$InetConstant",
      "sqlancer.yugabyte.ysql.ast.YSQLBinaryBitOperation$YSQLBinaryBitOperator",
      "sqlancer.common.schema.AbstractSchema",
      "sqlancer.yugabyte.ysql.YSQLSchema$YSQLDataType",
      "sqlancer.IgnoreMeException",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$ByteConstant",
      "sqlancer.yugabyte.ysql.YSQLSchema$YSQLColumn"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(YSQLBinaryBitOperation_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "sqlancer.common.ast.BinaryNode",
      "sqlancer.common.ast.BinaryOperatorNode",
      "sqlancer.yugabyte.ysql.ast.YSQLBinaryBitOperation",
      "sqlancer.yugabyte.ysql.ast.YSQLBinaryBitOperation$YSQLBinaryBitOperator",
      "sqlancer.yugabyte.ysql.YSQLSchema$YSQLDataType",
      "sqlancer.GlobalState",
      "sqlancer.SQLGlobalState",
      "sqlancer.ExpandedGlobalState",
      "sqlancer.yugabyte.ysql.YSQLGlobalState",
      "sqlancer.yugabyte.ysql.gen.YSQLExpressionGenerator",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$YSQLNullConstant",
      "sqlancer.Randomly$StringGenerationStrategy$4",
      "sqlancer.Randomly$StringGenerationStrategy",
      "sqlancer.Randomly",
      "sqlancer.yugabyte.ysql.ast.YSQLSelect$YSQLFromTable",
      "sqlancer.yugabyte.ysql.ast.YSQLConcatOperation",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$YSQLConstantBase",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$DecimalConstant",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$FloatConstant",
      "sqlancer.yugabyte.ysql.ast.YSQLPostfixOperation",
      "sqlancer.yugabyte.ysql.ast.YSQLSimilarTo",
      "sqlancer.yugabyte.ysql.ast.YSQLCollate",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$BooleanConstant",
      "sqlancer.common.ast.SelectBase",
      "sqlancer.yugabyte.ysql.ast.YSQLSelect",
      "sqlancer.common.ast.SelectBase$SelectType",
      "sqlancer.yugabyte.ysql.ast.YSQLSelect$YSQLSubquery",
      "sqlancer.common.ast.JoinBase",
      "sqlancer.yugabyte.ysql.ast.YSQLJoin",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$StringConstant",
      "sqlancer.yugabyte.ysql.ast.YSQLBinaryArithmeticOperation",
      "sqlancer.yugabyte.ysql.ast.YSQLPrefixOperation",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$IntConstant",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$ByteConstant",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$RangeConstant",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$DoubleConstant",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$InetConstant",
      "sqlancer.yugabyte.ysql.ast.YSQLConstant$BitConstant",
      "sqlancer.common.schema.AbstractTableColumn",
      "sqlancer.yugabyte.ysql.YSQLSchema$YSQLColumn",
      "sqlancer.yugabyte.ysql.ast.YSQLBetweenOperation",
      "sqlancer.yugabyte.ysql.ast.YSQLPostfixText",
      "sqlancer.yugabyte.ysql.ast.YSQLBinaryComparisonOperation",
      "sqlancer.yugabyte.ysql.ast.YSQLBinaryLogicalOperation",
      "sqlancer.yugabyte.ysql.YSQLCompoundDataType",
      "sqlancer.yugabyte.ysql.ast.YSQLCastOperation",
      "sqlancer.SQLConstantUtils",
      "sqlancer.yugabyte.ysql.ast.YSQLPOSIXRegularExpression",
      "sqlancer.yugabyte.ysql.ast.YSQLBinaryRangeOperation",
      "sqlancer.yugabyte.ysql.ast.YSQLColumnValue",
      "sqlancer.yugabyte.ysql.ast.YSQLFunction",
      "sqlancer.yugabyte.ysql.ast.YSQLInOperation",
      "sqlancer.yugabyte.ysql.ast.YSQLOrderByTerm",
      "sqlancer.IgnoreMeException",
      "sqlancer.common.ast.FunctionNode",
      "sqlancer.yugabyte.ysql.ast.YSQLAggregate",
      "sqlancer.yugabyte.ysql.ast.YSQLAlias",
      "sqlancer.common.query.Query",
      "sqlancer.common.query.SQLQueryAdapter",
      "sqlancer.common.query.ExpectedErrors",
      "sqlancer.common.schema.AbstractRowValue",
      "sqlancer.yugabyte.ysql.YSQLSchema$YSQLRowValue",
      "sqlancer.common.schema.TableIndex",
      "sqlancer.yugabyte.ysql.YSQLSchema$YSQLIndex",
      "sqlancer.yugabyte.ysql.YSQLSchema$YSQLStatisticsObject",
      "sqlancer.common.schema.AbstractTable",
      "sqlancer.common.schema.AbstractRelationalTable",
      "sqlancer.yugabyte.ysql.YSQLSchema$YSQLTable",
      "sqlancer.common.query.ExpectedErrors$ExpectedErrorsBuilder",
      "sqlancer.common.query.SQLQueryResultCheckAdapter",
      "sqlancer.ProviderAdapter",
      "sqlancer.SQLProviderAdapter",
      "sqlancer.ExpandedProvider",
      "sqlancer.oceanbase.ast.OceanBaseSelect",
      "sqlancer.oceanbase.ast.OceanBaseSelect$SelectType",
      "sqlancer.common.visitor.NodeVisitor",
      "sqlancer.common.visitor.ToStringVisitor",
      "sqlancer.yugabyte.ysql.YSQLToStringVisitor",
      "sqlancer.doris.DorisSchema$DorisTable",
      "sqlancer.postgres.PostgresGlobalState",
      "sqlancer.citus.CitusGlobalState"
    );
  }
}
