/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 07 13:34:40 GMT 2025
 */

package sqlancer.evosuite.questdb.test;

import static org.junit.jupiter.api.Assertions.fail;

import org.junit.jupiter.api.Test;

import sqlancer.questdb.QuestDBProvider;
import sqlancer.questdb.test.QuestDBQueryPartitioningWhereTester;

public class QuestDBQueryPartitioningWhereTester_ESTest {

    @Test
    public void test0() throws Throwable {
        QuestDBProvider.QuestDBGlobalState questDBProvider_QuestDBGlobalState0 = new QuestDBProvider.QuestDBGlobalState();
        QuestDBQueryPartitioningWhereTester questDBQueryPartitioningWhereTester0 = new QuestDBQueryPartitioningWhereTester(
                questDBProvider_QuestDBGlobalState0);
        // Undeclared exception!
        try {
            questDBQueryPartitioningWhereTester0.check();
            fail("Expecting exception: AssertionError");

        } catch (AssertionError e) {
            //
            // null
            //
        }
    }

    @Test
    public void test1() throws Throwable {
        QuestDBQueryPartitioningWhereTester questDBQueryPartitioningWhereTester0 = new QuestDBQueryPartitioningWhereTester(
                (QuestDBProvider.QuestDBGlobalState) null);
        // Undeclared exception!
        try {
            questDBQueryPartitioningWhereTester0.check();
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("sqlancer.questdb.test.QuestDBQueryPartitioningBase", e);
        }
    }

    private void verifyException(String s, NullPointerException e) {
    }
}
