/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Apr 07 13:00:32 GMT 2025
 */

package sqlancer.sqlite3.ast;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class SQLite3RowValueExpression_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "sqlancer.sqlite3.ast.SQLite3RowValueExpression"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\yewjo\\OneDrive\\Desktop\\NUS\\y4s2\\cs3213\\project\\sqlancer"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\yewjo\\AppData\\Local\\Temp\\"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(SQLite3RowValueExpression_ESTest_scaffolding.class.getClassLoader() ,
      "sqlancer.sqlite3.ast.SQLite3Select",
      "sqlancer.MainOptions",
      "sqlancer.Randomly",
      "sqlancer.sqlite3.ast.SQLite3RowValueExpression",
      "sqlancer.sqlite3.ast.SQLite3CollateOperation",
      "sqlancer.sqlite3.ast.SQLite3Constant$SQLite3RealConstant",
      "sqlancer.sqlite3.schema.SQLite3Schema$SQLite3Column",
      "sqlancer.sqlite3.schema.SQLite3Schema",
      "sqlancer.sqlite3.ast.SQLite3Select$SelectType",
      "sqlancer.common.schema.AbstractTableColumn",
      "sqlancer.Randomly$StringGenerationStrategy",
      "sqlancer.sqlite3.ast.SQLite3Constant$SQLite3NullConstant",
      "sqlancer.common.ast.SelectBase$SelectType",
      "sqlancer.common.ast.newast.Expression",
      "sqlancer.Randomly$StringGenerationStrategy$4",
      "sqlancer.sqlite3.ast.SQLite3WindowFunctionExpression",
      "sqlancer.Randomly$StringGenerationStrategy$3",
      "sqlancer.Randomly$StringGenerationStrategy$2",
      "sqlancer.Randomly$StringGenerationStrategy$1",
      "sqlancer.sqlite3.ast.SQLite3WindowFunctionExpression$SQLite3FrameSpecKind",
      "sqlancer.common.ast.newast.Select",
      "sqlancer.sqlite3.ast.SQLite3Constant",
      "sqlancer.common.schema.AbstractSchema",
      "sqlancer.sqlite3.ast.SQLite3Constant$SQLite3IntConstant",
      "sqlancer.sqlite3.schema.SQLite3Schema$SQLite3Column$SQLite3CollateSequence",
      "sqlancer.sqlite3.ast.SQLite3TypeAffinity",
      "sqlancer.sqlite3.schema.SQLite3DataType",
      "sqlancer.IgnoreMeException",
      "sqlancer.common.ast.SelectBase",
      "sqlancer.sqlite3.ast.SQLite3WindowFunctionExpression$SQLite3FrameSpecExclude",
      "sqlancer.sqlite3.ast.SQLite3Constant$SQLite3BinaryConstant",
      "sqlancer.sqlite3.ast.SQLite3Constant$SQLite3TextConstant",
      "sqlancer.sqlite3.ast.SQLite3Expression"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(SQLite3RowValueExpression_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "sqlancer.sqlite3.ast.SQLite3RowValueExpression",
      "sqlancer.sqlite3.ast.SQLite3Constant",
      "sqlancer.sqlite3.ast.SQLite3Constant$SQLite3TextConstant",
      "sqlancer.sqlite3.ast.SQLite3WindowFunctionExpression",
      "sqlancer.sqlite3.schema.SQLite3DataType",
      "sqlancer.sqlite3.ast.SQLite3TypeAffinity",
      "sqlancer.Randomly$StringGenerationStrategy$4",
      "sqlancer.Randomly$StringGenerationStrategy",
      "sqlancer.Randomly",
      "sqlancer.common.ast.SelectBase",
      "sqlancer.sqlite3.ast.SQLite3Select",
      "sqlancer.sqlite3.ast.SQLite3Aggregate",
      "sqlancer.common.visitor.NodeVisitor",
      "sqlancer.common.visitor.ToStringVisitor",
      "sqlancer.sqlite3.SQLite3ToStringVisitor",
      "sqlancer.sqlite3.ast.SQLite3WindowFunctionExpression$SQLite3WindowFunctionFrameSpecTerm",
      "sqlancer.sqlite3.ast.SQLite3Constant$SQLite3BinaryConstant",
      "sqlancer.sqlite3.ast.SQLite3Cast",
      "sqlancer.sqlite3.ast.SQLite3Constant$SQLite3RealConstant",
      "sqlancer.sqlite3.ast.SQLite3Constant$SQLite3IntConstant",
      "sqlancer.sqlite3.ast.SQLite3WindowFunction",
      "sqlancer.sqlite3.ast.SQLite3Function",
      "sqlancer.sqlite3.ast.SQLite3PostfixUnaryOperation",
      "sqlancer.ProviderAdapter",
      "sqlancer.SQLProviderAdapter",
      "sqlancer.sqlite3.SQLite3Provider",
      "sqlancer.sqlite3.ast.SQLite3CollateOperation",
      "sqlancer.sqlite3.ast.SQLite3MatchOperation",
      "sqlancer.sqlite3.ast.SQLite3OrderingTerm",
      "sqlancer.sqlite3.ast.SQLite3InOperation",
      "sqlancer.sqlite3.ast.SQLite3Constant$SQLite3NullConstant",
      "sqlancer.sqlite3.ast.SQLite3Exist",
      "sqlancer.sqlite3.ast.SQLite3Distinct",
      "sqlancer.SQLCastUtils",
      "sqlancer.sqlite3.ast.SQLite3PostfixText",
      "sqlancer.sqlite3.ast.SQLite3BinaryComparisonOperation",
      "sqlancer.sqlite3.ast.SQLite3BetweenOperation",
      "sqlancer.sqlite3.ast.SQLite3BinaryOperation",
      "sqlancer.sqlite3.ast.SQLite3Subquery",
      "sqlancer.sqlite3.ast.SQLite3TypeLiteral",
      "sqlancer.sqlite3.ast.SQLite3ExpressionCast",
      "sqlancer.sqlite3.ast.SQLite3ColumnName",
      "sqlancer.common.schema.AbstractTableColumn",
      "sqlancer.sqlite3.schema.SQLite3Schema$SQLite3Column",
      "sqlancer.common.ast.JoinBase",
      "sqlancer.sqlite3.ast.SQLite3Join",
      "sqlancer.sqlite3.ast.SQLite3UnaryOperation",
      "sqlancer.common.schema.AbstractTable",
      "sqlancer.common.schema.AbstractRelationalTable",
      "sqlancer.sqlite3.schema.SQLite3Schema$SQLite3Table",
      "sqlancer.sqlite3.ast.SQLite3Case",
      "sqlancer.sqlite3.ast.SQLite3Case$SQLite3CaseWithoutBaseExpression",
      "sqlancer.sqlite3.ast.SQLite3Case$CasePair",
      "sqlancer.sqlite3.ast.SQLite3Case$SQLite3CaseWithBaseExpression",
      "sqlancer.sqlite3.ast.SQLite3ExpressionFunction",
      "sqlancer.sqlite3.ast.SQLite3SetClause",
      "sqlancer.sqlite3.ast.SQLite3WindowFunctionExpression$SQLite3WindowFunctionFrameSpecBetween",
      "sqlancer.LikeImplementationHelper",
      "sqlancer.sqlite3.ast.SQLite3Text",
      "sqlancer.sqlite3.ast.SQLite3AffinityHelper",
      "sqlancer.sqlite3.ast.SQLite3AffinityHelper$ConstantTuple",
      "sqlancer.GlobalState",
      "sqlancer.SQLGlobalState",
      "sqlancer.sqlite3.SQLite3GlobalState",
      "sqlancer.sqlite3.ast.SQLite3TableReference",
      "sqlancer.sqlite3.SQLite3CollateHelper",
      "sqlancer.sqlite3.gen.SQLite3ExpressionGenerator",
      "sqlancer.hsqldb.HSQLDBSchema$HSQLDBTable",
      "sqlancer.IgnoreMeException",
      "sqlancer.presto.PrestoSchema$PrestoCompositeDataType",
      "sqlancer.presto.PrestoSchema$PrestoColumn",
      "sqlancer.common.ast.SelectBase$SelectType",
      "sqlancer.sqlite3.ast.SQLite3Select$SelectType"
    );
  }
}
