/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 07 13:28:23 GMT 2025
 */

package sqlancer.evosuite.databend.ast;

import org.junit.jupiter.api.Test;

import sqlancer.databend.ast.DatabendBinaryOperation;

import sqlancer.databend.ast.DatabendExpression;
import sqlancer.h2.H2ExpressionGenerator;

public class DatabendBinaryOperation_ESTest {

    @Test
    public void test0() throws Throwable {
        H2ExpressionGenerator.H2UnaryPostfixOperator h2ExpressionGenerator_H2UnaryPostfixOperator0 = H2ExpressionGenerator.H2UnaryPostfixOperator.IS_UNKNOWN;
        DatabendBinaryOperation databendBinaryOperation0 = new DatabendBinaryOperation((DatabendExpression) null,
                (DatabendExpression) null, h2ExpressionGenerator_H2UnaryPostfixOperator0);
    }
}
