/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 07 12:58:29 GMT 2025
 */

package sqlancer.evosuite.oceanbase;

import org.junit.jupiter.api.Test;

import sqlancer.oceanbase.OceanBaseUserCheckException;

public class OceanBaseUserCheckException_ESTest {

    @Test
    public void test0() throws Throwable {
        OceanBaseUserCheckException oceanBaseUserCheckException0 = new OceanBaseUserCheckException(
                "<L]F-AJW'Yq;JaQ&Z3");
    }
}
