/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 07 14:09:06 GMT 2025
 */

package sqlancer.evosuite.cnosdb.ast;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

import sqlancer.cnosdb.CnosDBSchema;
import sqlancer.cnosdb.ast.CnosDBConstant;
import sqlancer.cnosdb.ast.CnosDBLikeOperation;
import sqlancer.cnosdb.ast.CnosDBSelect;

//@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class CnosDBLikeOperation_ESTest {

    @Test
    public void test0() throws Throwable {
        CnosDBConstant cnosDBConstant0 = CnosDBConstant.createTimeStampConstant(935L);
        CnosDBLikeOperation cnosDBLikeOperation0 = new CnosDBLikeOperation(cnosDBConstant0, cnosDBConstant0);
        String string0 = cnosDBLikeOperation0.getOperatorRepresentation();
        assertEquals("LIKE", string0);
    }

    @Test
    public void test1() throws Throwable {
        CnosDBSelect cnosDBSelect0 = new CnosDBSelect();
        CnosDBLikeOperation cnosDBLikeOperation0 = new CnosDBLikeOperation(cnosDBSelect0, cnosDBSelect0);
        CnosDBSchema.CnosDBDataType cnosDBSchema_CnosDBDataType0 = cnosDBLikeOperation0.getExpressionType();
        assertEquals(CnosDBSchema.CnosDBDataType.BOOLEAN, cnosDBSchema_CnosDBDataType0);
    }
}
