/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 07 13:36:39 GMT 2025
 */

package sqlancer.yugabyte.ycql.ast;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sqlancer.doris.ast.DorisLikeOperation;
import sqlancer.yugabyte.ycql.ast.YCQLBinaryOperation;
import sqlancer.yugabyte.ycql.ast.YCQLConstant;
import sqlancer.yugabyte.ycql.ast.YCQLExpression;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class YCQLBinaryOperation_ESTest extends YCQLBinaryOperation_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      YCQLExpression yCQLExpression0 = YCQLConstant.createIntConstant(1665L);
      DorisLikeOperation.DorisLikeOperator dorisLikeOperation_DorisLikeOperator0 = DorisLikeOperation.DorisLikeOperator.LIKE_OPERATOR;
      YCQLBinaryOperation yCQLBinaryOperation0 = new YCQLBinaryOperation(yCQLExpression0, yCQLExpression0, dorisLikeOperation_DorisLikeOperator0);
  }
}
