/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Apr 07 13:16:08 GMT 2025
 */

package sqlancer.duckdb.test;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class DuckDBQueryPartitioningBase_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "sqlancer.duckdb.test.DuckDBQueryPartitioningBase"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\yewjo\\OneDrive\\Desktop\\NUS\\y4s2\\cs3213\\project\\sqlancer"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\yewjo\\AppData\\Local\\Temp\\"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(DuckDBQueryPartitioningBase_ESTest_scaffolding.class.getClassLoader() ,
      "sqlancer.duckdb.ast.DuckDBExpression",
      "sqlancer.AbstractAction",
      "sqlancer.common.gen.NoRECGenerator",
      "sqlancer.StatementExecutor",
      "sqlancer.SQLProviderAdapter",
      "sqlancer.common.gen.ExpressionGenerator",
      "sqlancer.common.ast.newast.NewFunctionNode",
      "sqlancer.Randomly$StringGenerationStrategy",
      "sqlancer.Main$StateLogger",
      "sqlancer.duckdb.test.DuckDBQueryPartitioningBase",
      "sqlancer.duckdb.DuckDBSchema",
      "sqlancer.common.schema.AbstractTable",
      "sqlancer.common.query.ExpectedErrors",
      "sqlancer.GlobalState",
      "sqlancer.duckdb.DuckDBErrors",
      "sqlancer.common.ast.newast.Select",
      "sqlancer.common.gen.UntypedExpressionGenerator",
      "sqlancer.duckdb.ast.DuckDBFunction",
      "sqlancer.common.schema.AbstractSchema",
      "sqlancer.duckdb.gen.DuckDBExpressionGenerator",
      "sqlancer.DatabaseProvider",
      "sqlancer.duckdb.DuckDBSchema$DuckDBTable",
      "sqlancer.common.gen.PartitionGenerator",
      "sqlancer.common.schema.AbstractRelationalTable",
      "sqlancer.Main$QueryManager",
      "sqlancer.duckdb.DuckDBProvider",
      "sqlancer.ProviderAdapter",
      "sqlancer.common.query.Query",
      "sqlancer.SQLancerDBConnection",
      "sqlancer.duckdb.DuckDBProvider$Action",
      "sqlancer.MainOptions",
      "sqlancer.common.ast.newast.ColumnReferenceNode",
      "sqlancer.duckdb.DuckDBSchema$DuckDBDataType",
      "sqlancer.Randomly",
      "sqlancer.duckdb.DuckDBProvider$DuckDBGlobalState",
      "sqlancer.duckdb.DuckDBSchema$DuckDBCompositeDataType",
      "sqlancer.duckdb.ast.DuckDBColumnReference",
      "sqlancer.common.oracle.TestOracle",
      "sqlancer.common.gen.TLPWhereGenerator",
      "sqlancer.common.schema.AbstractTableColumn",
      "sqlancer.common.query.SQLancerResultSet",
      "sqlancer.common.ast.newast.Expression",
      "sqlancer.duckdb.DuckDBSchema$DuckDBTables",
      "sqlancer.SQLGlobalState",
      "sqlancer.common.ast.BinaryOperatorNode$Operator",
      "sqlancer.Randomly$StringGenerationStrategy$4",
      "sqlancer.StateToReproduce",
      "sqlancer.Randomly$StringGenerationStrategy$3",
      "sqlancer.duckdb.gen.DuckDBExpressionGenerator$DuckDBAggregateFunction",
      "sqlancer.Randomly$StringGenerationStrategy$2",
      "sqlancer.Randomly$StringGenerationStrategy$1",
      "sqlancer.duckdb.ast.DuckDBSelect",
      "sqlancer.SQLConnection",
      "sqlancer.duckdb.ast.DuckDBTableReference",
      "sqlancer.duckdb.DuckDBSchema$DuckDBColumn",
      "sqlancer.DBMSSpecificOptions",
      "sqlancer.IgnoreMeException",
      "sqlancer.common.log.Loggable",
      "sqlancer.common.ast.SelectBase",
      "sqlancer.SQLErrorsUtils",
      "sqlancer.common.schema.AbstractTables",
      "sqlancer.common.oracle.TernaryLogicPartitioningOracleBase",
      "sqlancer.Reproducer",
      "sqlancer.common.ast.newast.TableReferenceNode"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(DuckDBQueryPartitioningBase_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "sqlancer.common.oracle.TernaryLogicPartitioningOracleBase",
      "sqlancer.duckdb.test.DuckDBQueryPartitioningBase",
      "sqlancer.common.ast.JoinBase",
      "sqlancer.duckdb.ast.DuckDBJoin",
      "sqlancer.common.ast.JoinBase$JoinType",
      "sqlancer.Randomly$StringGenerationStrategy$4",
      "sqlancer.Randomly$StringGenerationStrategy",
      "sqlancer.Randomly",
      "sqlancer.duckdb.ast.DuckDBJoin$OuterType",
      "sqlancer.GlobalState",
      "sqlancer.SQLGlobalState",
      "sqlancer.duckdb.DuckDBProvider$DuckDBGlobalState",
      "sqlancer.common.query.ExpectedErrors",
      "sqlancer.duckdb.DuckDBErrors",
      "sqlancer.SQLErrorsUtils",
      "sqlancer.SQLConnection",
      "sqlancer.common.schema.AbstractSchema",
      "sqlancer.duckdb.DuckDBSchema",
      "sqlancer.duckdb.ast.DuckDBConstant",
      "sqlancer.duckdb.ast.DuckDBConstant$DuckDBDateConstant",
      "sqlancer.common.query.Query",
      "sqlancer.common.query.SQLQueryAdapter",
      "sqlancer.common.query.SQLQueryResultCheckAdapter",
      "sqlancer.common.gen.UntypedExpressionGenerator",
      "sqlancer.duckdb.gen.DuckDBExpressionGenerator",
      "sqlancer.common.query.ExpectedErrors$ExpectedErrorsBuilder",
      "sqlancer.hsqldb.HSQLDBProvider$HSQLDBGlobalState",
      "sqlancer.common.ast.SelectBase",
      "sqlancer.duckdb.ast.DuckDBSelect",
      "sqlancer.common.ast.SelectBase$SelectType",
      "sqlancer.mysql.ast.MySQLSelect",
      "sqlancer.mysql.ast.MySQLSelect$SelectType",
      "sqlancer.oceanbase.ast.OceanBaseSelect",
      "sqlancer.oceanbase.ast.OceanBaseSelect$SelectType",
      "sqlancer.common.schema.AbstractTables",
      "sqlancer.duckdb.DuckDBSchema$DuckDBTables",
      "sqlancer.duckdb.DuckDBSchema$DuckDBCompositeDataType",
      "sqlancer.common.schema.AbstractTableColumn",
      "sqlancer.duckdb.DuckDBSchema$DuckDBColumn",
      "sqlancer.common.schema.AbstractTable",
      "sqlancer.common.schema.AbstractRelationalTable",
      "sqlancer.duckdb.DuckDBSchema$DuckDBTable",
      "sqlancer.ExpandedGlobalState",
      "sqlancer.materialize.MaterializeGlobalState",
      "sqlancer.duckdb.ast.DuckDBConstant$DuckDBTimestampConstant",
      "sqlancer.common.ast.newast.NewFunctionNode",
      "sqlancer.duckdb.ast.DuckDBFunction",
      "sqlancer.common.ast.newast.NewBetweenOperatorNode",
      "sqlancer.duckdb.ast.DuckDBBetweenOperator",
      "sqlancer.common.ast.newast.TableReferenceNode",
      "sqlancer.duckdb.ast.DuckDBTableReference",
      "sqlancer.common.ast.newast.NewUnaryPrefixOperatorNode",
      "sqlancer.duckdb.ast.DuckDBUnaryPrefixOperator",
      "sqlancer.duckdb.gen.DuckDBExpressionGenerator$DuckDBUnaryPrefixOperator",
      "sqlancer.duckdb.ast.DuckDBConstant$DuckDBIntConstant",
      "sqlancer.common.ast.newast.NewUnaryPostfixOperatorNode",
      "sqlancer.duckdb.ast.DuckDBUnaryPostfixOperator",
      "sqlancer.common.ast.newast.NewPostfixTextNode",
      "sqlancer.duckdb.ast.DuckDBPostFixText",
      "sqlancer.duckdb.gen.DuckDBExpressionGenerator$DuckDBCastOperation",
      "sqlancer.common.ast.newast.NewToStringVisitor",
      "sqlancer.duckdb.DuckDBToStringVisitor",
      "sqlancer.duckdb.ast.DuckDBConstant$DuckDBBooleanConstant",
      "sqlancer.common.ast.newast.NewCaseOperatorNode",
      "sqlancer.duckdb.ast.DuckDBCaseOperator",
      "sqlancer.duckdb.ast.DuckDBConstant$DuckDBTextConstant",
      "sqlancer.common.ast.newast.ColumnReferenceNode",
      "sqlancer.duckdb.ast.DuckDBColumnReference",
      "sqlancer.duckdb.gen.DuckDBExpressionGenerator$DuckDBUnaryPostfixOperator",
      "sqlancer.duckdb.ast.DuckDBConstant$DuckDBDoubleConstant",
      "sqlancer.common.ast.newast.NewAliasNode",
      "sqlancer.duckdb.ast.DuckDBAlias",
      "sqlancer.oceanbase.ast.OceanBaseConstant",
      "sqlancer.oceanbase.ast.OceanBaseConstant$OceanBaseTextConstant",
      "sqlancer.oceanbase.ast.OceanBaseConstant$OceanBaseIntConstant",
      "sqlancer.SQLConstantUtils",
      "sqlancer.SQLConstantUtils$CastType",
      "sqlancer.mysql.ast.MySQLConstant",
      "sqlancer.mysql.ast.MySQLConstant$MySQLIntConstant",
      "sqlancer.duckdb.ast.DuckDBConstant$DuckDBNullConstant",
      "sqlancer.IgnoreMeException",
      "sqlancer.duckdb.gen.DuckDBExpressionGenerator$DuckDBCastOperation$1",
      "sqlancer.postgres.ast.PostgresBinaryArithmeticOperation$PostgresBinaryOperator"
    );
  }
}
