/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Apr 07 14:07:36 GMT 2025
 */

package sqlancer.oceanbase.ast;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class OceanBaseExists_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "sqlancer.oceanbase.ast.OceanBaseExists"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\yewjo\\OneDrive\\Desktop\\NUS\\y4s2\\cs3213\\project\\sqlancer"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\yewjo\\AppData\\Local\\Temp\\"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(OceanBaseExists_ESTest_scaffolding.class.getClassLoader() ,
      "sqlancer.SQLConstantUtils",
      "sqlancer.Randomly",
      "sqlancer.oceanbase.ast.OceanBaseBinaryComparisonOperation$BinaryComparisonOperator$5",
      "sqlancer.oceanbase.ast.OceanBaseBinaryComparisonOperation$BinaryComparisonOperator",
      "sqlancer.oceanbase.ast.OceanBaseBinaryComparisonOperation$BinaryComparisonOperator$4",
      "sqlancer.oceanbase.ast.OceanBaseBinaryComparisonOperation$BinaryComparisonOperator$6",
      "sqlancer.oceanbase.ast.OceanBaseConstant$OceanBaseTextConstant",
      "sqlancer.oceanbase.OceanBaseSchema$OceanBaseColumn",
      "sqlancer.common.schema.AbstractTableColumn",
      "sqlancer.oceanbase.ast.OceanBaseBinaryComparisonOperation",
      "sqlancer.Randomly$StringGenerationStrategy",
      "sqlancer.oceanbase.OceanBaseSchema",
      "sqlancer.oceanbase.ast.OceanBaseBinaryComparisonOperation$BinaryComparisonOperator$1",
      "sqlancer.oceanbase.ast.OceanBaseBinaryLogicalOperation$OceanBaseBinaryLogicalOperator",
      "sqlancer.oceanbase.ast.OceanBaseConstant$OceanBaseIntConstant",
      "sqlancer.oceanbase.ast.OceanBaseBinaryComparisonOperation$BinaryComparisonOperator$3",
      "sqlancer.common.ast.SelectBase$SelectType",
      "sqlancer.oceanbase.ast.OceanBaseConstant$OceanBaseNoPQSConstant",
      "sqlancer.oceanbase.ast.OceanBaseBinaryComparisonOperation$BinaryComparisonOperator$2",
      "sqlancer.common.ast.newast.Expression",
      "sqlancer.Randomly$StringGenerationStrategy$4",
      "sqlancer.Randomly$StringGenerationStrategy$3",
      "sqlancer.Randomly$StringGenerationStrategy$2",
      "sqlancer.Randomly$StringGenerationStrategy$1",
      "sqlancer.common.ast.newast.Select",
      "sqlancer.oceanbase.ast.OceanBaseCastOperation$CastType",
      "sqlancer.oceanbase.ast.OceanBaseSelect$SelectType",
      "sqlancer.oceanbase.ast.OceanBaseSelect",
      "sqlancer.oceanbase.OceanBaseSchema$OceanBaseDataType",
      "sqlancer.common.schema.AbstractSchema",
      "sqlancer.oceanbase.ast.OceanBaseConstant$OceanBaseDoubleConstant",
      "sqlancer.common.schema.AbstractBinaryLogicalOperation",
      "sqlancer.oceanbase.ast.OceanBaseConstant",
      "sqlancer.oceanbase.ast.OceanBaseBinaryLogicalOperation$OceanBaseBinaryLogicalOperator$1",
      "sqlancer.oceanbase.ast.OceanBaseBinaryLogicalOperation$OceanBaseBinaryLogicalOperator$2",
      "sqlancer.oceanbase.ast.OceanBaseBinaryLogicalOperation$OceanBaseBinaryLogicalOperator$3",
      "sqlancer.oceanbase.ast.OceanBaseExists",
      "sqlancer.oceanbase.ast.OceanBaseExpression",
      "sqlancer.oceanbase.ast.OceanBaseCastOperation",
      "sqlancer.oceanbase.ast.OceanBaseConstant$OceanBaseNullConstant",
      "sqlancer.IgnoreMeException",
      "sqlancer.common.ast.SelectBase",
      "sqlancer.oceanbase.ast.OceanBaseBinaryLogicalOperation",
      "sqlancer.oceanbase.ast.OceanBaseStringExpression"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(OceanBaseExists_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "sqlancer.oceanbase.ast.OceanBaseExists",
      "sqlancer.common.schema.AbstractTableColumn",
      "sqlancer.oceanbase.OceanBaseSchema$OceanBaseColumn",
      "sqlancer.oceanbase.ast.OceanBaseConstant",
      "sqlancer.oceanbase.ast.OceanBaseConstant$OceanBaseIntConstant",
      "sqlancer.Randomly$StringGenerationStrategy$4",
      "sqlancer.Randomly$StringGenerationStrategy",
      "sqlancer.Randomly",
      "sqlancer.oceanbase.ast.OceanBaseConstant$OceanBaseNoPQSConstant",
      "sqlancer.oceanbase.ast.OceanBaseConstant$OceanBaseDoubleConstant",
      "sqlancer.oceanbase.ast.OceanBaseColumnReference",
      "sqlancer.oceanbase.ast.OceanBaseAggregate",
      "sqlancer.common.ast.SelectBase",
      "sqlancer.oceanbase.ast.OceanBaseSelect",
      "sqlancer.common.ast.SelectBase$SelectType",
      "sqlancer.oceanbase.ast.OceanBaseSelect$SelectType",
      "sqlancer.oceanbase.ast.OceanBaseConstant$OceanBaseTextConstant",
      "sqlancer.oceanbase.ast.OceanBaseConstant$OceanBaseNullConstant",
      "sqlancer.IgnoreMeException",
      "sqlancer.oceanbase.ast.OceanBaseBinaryComparisonOperation",
      "sqlancer.oceanbase.ast.OceanBaseBinaryLogicalOperation",
      "sqlancer.common.ast.JoinBase",
      "sqlancer.oceanbase.ast.OceanBaseJoin",
      "sqlancer.SQLConstantUtils",
      "sqlancer.SQLConstantUtils$CastType",
      "sqlancer.mysql.ast.MySQLConstant",
      "sqlancer.mysql.ast.MySQLConstant$MySQLIntConstant",
      "sqlancer.common.ast.UnaryNode",
      "sqlancer.common.ast.UnaryOperatorNode",
      "sqlancer.oceanbase.ast.OceanBaseUnaryPrefixOperation",
      "sqlancer.oceanbase.ast.OceanBaseComputableFunction",
      "sqlancer.oceanbase.ast.OceanBaseCastOperation",
      "sqlancer.oceanbase.ast.OceanBaseColumnName",
      "sqlancer.oceanbase.ast.OceanBaseOrderByTerm",
      "sqlancer.oceanbase.ast.OceanBaseInOperation",
      "sqlancer.oceanbase.ast.OceanBaseText",
      "sqlancer.oceanbase.OceanBaseSchema$OceanBaseDataType"
    );
  }
}
