/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Apr 07 14:03:36 GMT 2025
 */

package sqlancer.duckdb.ast;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class DuckDBSelect_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "sqlancer.duckdb.ast.DuckDBSelect"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\yewjo\\OneDrive\\Desktop\\NUS\\y4s2\\cs3213\\project\\sqlancer"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\yewjo\\AppData\\Local\\Temp\\"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(DuckDBSelect_ESTest_scaffolding.class.getClassLoader() ,
      "sqlancer.MainOptions",
      "sqlancer.duckdb.ast.DuckDBExpression",
      "sqlancer.common.ast.newast.ColumnReferenceNode",
      "sqlancer.Randomly",
      "sqlancer.duckdb.DuckDBSchema$DuckDBDataType",
      "sqlancer.common.ast.newast.NewOrderingTerm",
      "sqlancer.common.ast.newast.NewPostfixTextNode",
      "sqlancer.duckdb.DuckDBSchema$DuckDBCompositeDataType",
      "sqlancer.SQLProviderAdapter",
      "sqlancer.common.ast.newast.NewFunctionNode",
      "sqlancer.common.ast.newast.NewToStringVisitor",
      "sqlancer.common.schema.AbstractTableColumn",
      "sqlancer.common.ast.newast.NewCaseOperatorNode",
      "sqlancer.common.ast.newast.NewAliasNode",
      "sqlancer.Randomly$StringGenerationStrategy",
      "sqlancer.common.ast.SelectBase$SelectType",
      "sqlancer.common.ast.newast.Expression",
      "sqlancer.duckdb.DuckDBSchema",
      "sqlancer.common.ast.newast.NewTernaryNode",
      "sqlancer.Randomly$StringGenerationStrategy$4",
      "sqlancer.Randomly$StringGenerationStrategy$3",
      "sqlancer.common.schema.AbstractTable",
      "sqlancer.Randomly$StringGenerationStrategy$2",
      "sqlancer.common.ast.newast.NewBinaryOperatorNode",
      "sqlancer.Randomly$StringGenerationStrategy$1",
      "sqlancer.common.ast.newast.Select",
      "sqlancer.common.schema.AbstractSchema",
      "sqlancer.duckdb.ast.DuckDBSelect",
      "sqlancer.common.ast.newast.Join",
      "sqlancer.duckdb.DuckDBSchema$DuckDBColumn",
      "sqlancer.duckdb.ast.DuckDBTableReference",
      "sqlancer.DatabaseProvider",
      "sqlancer.common.ast.newast.NewBetweenOperatorNode",
      "sqlancer.duckdb.ast.DuckDBConstant",
      "sqlancer.duckdb.DuckDBToStringVisitor",
      "sqlancer.common.ast.newast.NewInOperatorNode",
      "sqlancer.duckdb.DuckDBSchema$DuckDBTable",
      "sqlancer.common.schema.AbstractRelationalTable",
      "sqlancer.IgnoreMeException",
      "sqlancer.duckdb.DuckDBProvider",
      "sqlancer.common.ast.newast.NewUnaryPrefixOperatorNode",
      "sqlancer.common.ast.SelectBase",
      "sqlancer.duckdb.ast.DuckDBJoin",
      "sqlancer.ProviderAdapter",
      "sqlancer.common.ast.JoinBase",
      "sqlancer.common.ast.newast.NewUnaryPostfixOperatorNode",
      "sqlancer.common.ast.newast.TableReferenceNode"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(DuckDBSelect_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "sqlancer.common.ast.SelectBase",
      "sqlancer.duckdb.ast.DuckDBSelect",
      "sqlancer.duckdb.ast.DuckDBConstant",
      "sqlancer.duckdb.ast.DuckDBConstant$DuckDBDoubleConstant",
      "sqlancer.Randomly$StringGenerationStrategy$4",
      "sqlancer.Randomly$StringGenerationStrategy",
      "sqlancer.Randomly",
      "sqlancer.common.ast.newast.NewCaseOperatorNode",
      "sqlancer.duckdb.ast.DuckDBCaseOperator",
      "sqlancer.common.ast.newast.NewToStringVisitor",
      "sqlancer.duckdb.DuckDBToStringVisitor",
      "sqlancer.duckdb.ast.DuckDBConstant$DuckDBBooleanConstant",
      "sqlancer.common.schema.AbstractTable",
      "sqlancer.common.schema.AbstractRelationalTable",
      "sqlancer.duckdb.DuckDBSchema$DuckDBTable",
      "sqlancer.duckdb.DuckDBSchema$DuckDBCompositeDataType",
      "sqlancer.common.schema.AbstractTableColumn",
      "sqlancer.duckdb.DuckDBSchema$DuckDBColumn",
      "sqlancer.common.ast.newast.TableReferenceNode",
      "sqlancer.duckdb.ast.DuckDBTableReference",
      "sqlancer.common.ast.JoinBase",
      "sqlancer.duckdb.ast.DuckDBJoin",
      "sqlancer.common.ast.newast.NewUnaryPostfixOperatorNode",
      "sqlancer.duckdb.gen.DuckDBExpressionGenerator$DuckDBCastOperation",
      "sqlancer.duckdb.gen.DuckDBExpressionGenerator$DuckDBCastOperation$1",
      "sqlancer.common.ast.newast.NewInOperatorNode",
      "sqlancer.duckdb.ast.DuckDBInOperator",
      "sqlancer.duckdb.ast.DuckDBConstant$DuckDBBitConstant",
      "sqlancer.duckdb.ast.DuckDBConstant$DuckDBDateConstant",
      "sqlancer.common.ast.newast.NewAliasNode",
      "sqlancer.duckdb.ast.DuckDBAlias",
      "sqlancer.common.ast.newast.ColumnReferenceNode",
      "sqlancer.duckdb.ast.DuckDBColumnReference",
      "sqlancer.duckdb.ast.DuckDBConstant$DuckDBTimestampConstant",
      "sqlancer.duckdb.ast.DuckDBConstant$DuckDBIntConstant",
      "sqlancer.duckdb.ast.DuckDBConstant$DuckDBNullConstant",
      "sqlancer.duckdb.ast.DuckDBConstant$DuckDBTextConstant",
      "sqlancer.common.ast.newast.NewOrderingTerm",
      "sqlancer.duckdb.ast.DuckDBOrderingTerm",
      "sqlancer.common.ast.newast.NewBinaryOperatorNode",
      "sqlancer.duckdb.ast.DuckDBBinaryOperator",
      "sqlancer.common.ast.newast.NewFunctionNode",
      "sqlancer.duckdb.ast.DuckDBFunction",
      "sqlancer.common.ast.newast.NewPostfixTextNode",
      "sqlancer.duckdb.ast.DuckDBPostFixText",
      "sqlancer.common.ast.newast.NewTernaryNode",
      "sqlancer.duckdb.ast.DuckDBTernary",
      "sqlancer.h2.H2ExpressionGenerator$H2BinaryArithmeticOperator",
      "sqlancer.postgres.ast.PostgresPOSIXRegularExpression$POSIXRegex",
      "sqlancer.common.ast.newast.NewUnaryPrefixOperatorNode",
      "sqlancer.duckdb.ast.DuckDBUnaryPrefixOperator",
      "sqlancer.cockroachdb.ast.CockroachDBUnaryPostfixOperation$CockroachDBUnaryPostfixOperator",
      "sqlancer.duckdb.ast.DuckDBUnaryPostfixOperator",
      "sqlancer.common.ast.newast.NewBetweenOperatorNode",
      "sqlancer.duckdb.ast.DuckDBBetweenOperator",
      "sqlancer.tidb.TiDBSchema$TiDBCompositeDataType",
      "sqlancer.tidb.TiDBSchema$TiDBColumn",
      "sqlancer.cockroachdb.ast.CockroachDBBinaryComparisonOperator$CockroachDBComparisonOperator",
      "sqlancer.clickhouse.ast.ClickHouseUnaryFunctionOperation$ClickHouseUnaryFunctionOperator",
      "sqlancer.postgres.ast.PostgresPostfixOperation$PostfixOperator",
      "sqlancer.materialize.ast.MaterializeBinaryArithmeticOperation$MaterializeBinaryOperator",
      "sqlancer.materialize.ast.MaterializeBinaryRangeOperation$MaterializeBinaryRangeOperator",
      "sqlancer.h2.H2ExpressionGenerator$H2BinaryComparisonOperator",
      "sqlancer.tidb.ast.TiDBBinaryBitOperation$TiDBBinaryBitOperator",
      "sqlancer.databend.ast.DatabendUnaryPostfixOperation$DatabendUnaryPostfixOperator",
      "sqlancer.cnosdb.ast.CnosDBBinaryComparisonOperation$CnosDBBinaryComparisonOperator",
      "sqlancer.doris.ast.DorisLikeOperation$DorisLikeOperator",
      "sqlancer.postgres.ast.PostgresBinaryBitOperation$PostgresBinaryBitOperator",
      "sqlancer.databend.ast.DatabendBinaryComparisonOperation$DatabendBinaryComparisonOperator",
      "sqlancer.h2.H2ExpressionGenerator$H2UnaryPostfixOperator",
      "sqlancer.DatabendDorisPrestoConstant",
      "sqlancer.doris.ast.DorisConstant",
      "sqlancer.doris.ast.DorisConstant$DorisTemporalConstant",
      "sqlancer.doris.ast.DorisConstant$DorisDatetimeConstant",
      "sqlancer.databend.ast.DatabendBinaryLogicalOperation$DatabendBinaryLogicalOperator",
      "sqlancer.postgres.PostgresSchema$PostgresDataType",
      "sqlancer.postgres.ast.PostgresPrefixOperation$PrefixOperator",
      "sqlancer.hsqldb.HSQLDBSchema$HSQLDBDataType",
      "sqlancer.hsqldb.ast.HSQLDBUnaryPrefixOperation$HSQLDBUnaryPrefixOperator",
      "sqlancer.tidb.ast.TiDBUnaryPostfixOperation$TiDBUnaryPostfixOperator",
      "sqlancer.cockroachdb.ast.CockroachDBUnaryArithmeticOperation$CockroachDBUnaryAritmeticOperator",
      "sqlancer.tidb.ast.TiDBBinaryArithmeticOperation$TiDBBinaryArithmeticOperator",
      "sqlancer.cnosdb.CnosDBSchema$CnosDBDataType",
      "sqlancer.cnosdb.ast.CnosDBPrefixOperation$PrefixOperator",
      "sqlancer.materialize.ast.MaterializeBinaryComparisonOperation$MaterializeBinaryComparisonOperator",
      "sqlancer.cockroachdb.ast.CockroachDBBinaryLogicalOperation$CockroachDBBinaryLogicalOperator",
      "sqlancer.doris.ast.DorisConstant$DorisTextConstant",
      "sqlancer.doris.ast.DorisConstant$DorisBooleanConstant",
      "sqlancer.hsqldb.ast.HSQLDBUnaryPostfixOperation$HSQLDBUnaryPostfixOperator",
      "sqlancer.cnosdb.ast.CnosDBBinaryArithmeticOperation$CnosDBBinaryOperator",
      "sqlancer.materialize.MaterializeSchema$MaterializeDataType",
      "sqlancer.materialize.ast.MaterializePrefixOperation$PrefixOperator",
      "sqlancer.cnosdb.ast.CnosDBPostfixOperation$PostfixOperator",
      "sqlancer.SQLConstantUtils",
      "sqlancer.tidb.ast.TiDBBinaryComparisonOperation$TiDBComparisonOperator",
      "sqlancer.postgres.ast.PostgresBinaryLogicalOperation$BinaryLogicalOperator",
      "sqlancer.postgres.ast.PostgresBinaryComparisonOperation$PostgresBinaryComparisonOperator",
      "sqlancer.postgres.ast.PostgresBinaryArithmeticOperation$PostgresBinaryOperator",
      "sqlancer.materialize.ast.MaterializePOSIXRegularExpression$POSIXRegex",
      "sqlancer.postgres.ast.PostgresBinaryRangeOperation$PostgresBinaryRangeOperator",
      "sqlancer.tidb.ast.TiDBBinaryLogicalOperation$TiDBBinaryLogicalOperator",
      "sqlancer.databend.ast.DatabendConstant",
      "sqlancer.databend.ast.DatabendConstant$DatabendStringConstant",
      "sqlancer.databend.ast.DatabendBinaryArithmeticOperation",
      "sqlancer.tidb.TiDBSchema$TiDBTable",
      "sqlancer.cockroachdb.ast.CockroachDBBinaryArithmeticOperation$CockroachDBBinaryArithmeticOperator",
      "sqlancer.presto.ast.PrestoUnaryPostfixOperation$PrestoUnaryPostfixOperator",
      "sqlancer.presto.PrestoSchema$PrestoDataType",
      "sqlancer.databend.ast.DatabendUnaryPrefixOperation$DatabendUnaryPrefixOperator",
      "sqlancer.databend.ast.DatabendConstant$DatabendNullConstant",
      "sqlancer.databend.ast.DatabendConstant$DatabendNumericConstant",
      "sqlancer.databend.ast.DatabendConstant$DatabendFloatConstant",
      "sqlancer.materialize.ast.MaterializeBinaryBitOperation$MaterializeBinaryBitOperator",
      "sqlancer.oceanbase.ast.OceanBaseUnaryPrefixOperation$OceanBaseUnaryPrefixOperator",
      "sqlancer.h2.H2ExpressionGenerator$H2UnaryPrefixOperator",
      "sqlancer.postgres.ast.PostgresConstant",
      "sqlancer.postgres.ast.PostgresConstant$StringConstant",
      "sqlancer.mysql.ast.MySQLUnaryPrefixOperation$MySQLUnaryPrefixOperator",
      "sqlancer.oceanbase.ast.OceanBaseConstant",
      "sqlancer.oceanbase.ast.OceanBaseConstant$OceanBaseNullConstant",
      "sqlancer.tidb.ast.TiDBUnaryPrefixOperation$TiDBUnaryPrefixOperator",
      "sqlancer.tidb.ast.TiDBRegexOperation$TiDBRegexOperator",
      "sqlancer.GlobalState",
      "sqlancer.SQLGlobalState",
      "sqlancer.duckdb.DuckDBProvider$DuckDBGlobalState",
      "sqlancer.common.query.Query",
      "sqlancer.common.query.SQLQueryAdapter",
      "sqlancer.clickhouse.ast.ClickHouseUnaryPostfixOperation$ClickHouseUnaryPostfixOperator",
      "sqlancer.databend.ast.DatabendLikeOperation$DatabendLikeOperator",
      "sqlancer.postgres.ast.PostgresConstant$IntConstant",
      "sqlancer.common.ast.BinaryNode",
      "sqlancer.postgres.ast.PostgresConcatOperation",
      "sqlancer.common.query.ExpectedErrors",
      "sqlancer.IgnoreMeException",
      "sqlancer.clickhouse.ast.ClickHouseUnaryPrefixOperation$ClickHouseUnaryPrefixOperator",
      "sqlancer.materialize.ast.MaterializePostfixOperation$PostfixOperator",
      "sqlancer.materialize.ast.MaterializeBinaryLogicalOperation$BinaryLogicalOperator",
      "sqlancer.doris.ast.DorisBinaryLogicalOperation$DorisBinaryLogicalOperator",
      "sqlancer.databend.ast.DatabendSelect",
      "sqlancer.materialize.ast.MaterializeConstant",
      "sqlancer.materialize.ast.MaterializeConstant$IntConstant",
      "sqlancer.materialize.ast.MaterializeConstant$BooleanConstant",
      "sqlancer.tidb.ast.TiDBConstant",
      "sqlancer.tidb.ast.TiDBConstant$TiDBNullConstant",
      "sqlancer.tidb.ast.TiDBJoin",
      "sqlancer.common.ast.BinaryOperatorNode",
      "sqlancer.tidb.ast.TiDBBinaryComparisonOperation",
      "sqlancer.doris.ast.DorisConstant$DorisNumericConstant",
      "sqlancer.doris.ast.DorisConstant$DorisIntConstant",
      "sqlancer.mysql.ast.MySQLBinaryLogicalOperation",
      "sqlancer.cnosdb.ast.CnosDBBinaryLogicalOperation$BinaryLogicalOperator",
      "sqlancer.doris.DorisSchema$DorisDataType",
      "sqlancer.doris.ast.DorisUnaryPrefixOperation$DorisUnaryPrefixOperator",
      "sqlancer.common.ast.SelectBase$SelectType",
      "sqlancer.duckdb.DuckDBSchema$DuckDBDataType"
    );
  }
}
