/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 07 13:55:28 GMT 2025
 */

package sqlancer.evosuite.yugabyte.ysql.ast;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

import sqlancer.yugabyte.ysql.YSQLSchema;
import sqlancer.yugabyte.ysql.ast.YSQLBinaryBitOperation;
import sqlancer.yugabyte.ysql.ast.YSQLConstant;

public class YSQLBinaryBitOperation_ESTest {

    // @Test
    // public void test0() throws Throwable {
    // YSQLBinaryBitOperation.YSQLBinaryBitOperator ySQLBinaryBitOperation_YSQLBinaryBitOperator0 =
    // YSQLBinaryBitOperation.YSQLBinaryBitOperator
    // .getRandom();
    // String string0 = ySQLBinaryBitOperation_YSQLBinaryBitOperator0.getTextRepresentation();
    // assertEquals("||", string0);
    // }

    @Test
    public void test1() throws Throwable {
        YSQLBinaryBitOperation.YSQLBinaryBitOperator ySQLBinaryBitOperation_YSQLBinaryBitOperator0 = YSQLBinaryBitOperation.YSQLBinaryBitOperator.BITWISE_AND;
        YSQLConstant.YSQLNullConstant ySQLConstant_YSQLNullConstant0 = new YSQLConstant.YSQLNullConstant();
        YSQLBinaryBitOperation ySQLBinaryBitOperation0 = new YSQLBinaryBitOperation(
                ySQLBinaryBitOperation_YSQLBinaryBitOperator0, ySQLConstant_YSQLNullConstant0,
                ySQLConstant_YSQLNullConstant0);
        YSQLSchema.YSQLDataType ySQLSchema_YSQLDataType0 = ySQLBinaryBitOperation0.getExpressionType();
        assertEquals(YSQLSchema.YSQLDataType.BIT, ySQLSchema_YSQLDataType0);
    }
}
