/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 07 13:04:21 GMT 2025
 */

package sqlancer.evosuite.yugabyte.ysql.ast;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.fail;

import org.junit.jupiter.api.Test;

import sqlancer.yugabyte.ysql.ast.YSQLConstant;
import sqlancer.yugabyte.ysql.ast.YSQLExpression;
import sqlancer.yugabyte.ysql.ast.YSQLOrderByTerm;

public class YSQLOrderByTerm_ESTest {

    @Test
    public void test0() throws Throwable {
        YSQLOrderByTerm.YSQLOrder ySQLOrderByTerm_YSQLOrder0 = YSQLOrderByTerm.YSQLOrder.ASC;
        YSQLOrderByTerm ySQLOrderByTerm0 = new YSQLOrderByTerm((YSQLExpression) null, ySQLOrderByTerm_YSQLOrder0);
        YSQLOrderByTerm.YSQLOrder ySQLOrderByTerm_YSQLOrder1 = ySQLOrderByTerm0.getOrder();
        assertSame(ySQLOrderByTerm_YSQLOrder0, ySQLOrderByTerm_YSQLOrder1);
    }

    @Test
    public void test1() throws Throwable {
        YSQLOrderByTerm.YSQLOrder ySQLOrderByTerm_YSQLOrder0 = YSQLOrderByTerm.YSQLOrder.ASC;
        YSQLOrderByTerm ySQLOrderByTerm0 = new YSQLOrderByTerm((YSQLExpression) null, ySQLOrderByTerm_YSQLOrder0);
        YSQLExpression ySQLExpression0 = ySQLOrderByTerm0.getExpr();
        assertNull(ySQLExpression0);
    }

    @Test
    public void test2() throws Throwable {
        YSQLOrderByTerm.YSQLOrder ySQLOrderByTerm_YSQLOrder0 = YSQLOrderByTerm.YSQLOrder.getRandomOrder();
        assertEquals(YSQLOrderByTerm.YSQLOrder.ASC, ySQLOrderByTerm_YSQLOrder0);
    }

    @Test
    public void test3() throws Throwable {
        YSQLConstant.YSQLNullConstant ySQLConstant_YSQLNullConstant0 = new YSQLConstant.YSQLNullConstant();
        YSQLOrderByTerm.YSQLOrder ySQLOrderByTerm_YSQLOrder0 = YSQLOrderByTerm.YSQLOrder.ASC;
        YSQLOrderByTerm ySQLOrderByTerm0 = new YSQLOrderByTerm(ySQLConstant_YSQLNullConstant0,
                ySQLOrderByTerm_YSQLOrder0);
        // Undeclared exception!
        try {
            ySQLOrderByTerm0.getExpectedValue();
            fail("Expecting exception: AssertionError");

        } catch (AssertionError e) {
            //
            // sqlancer.yugabyte.ysql.ast.YSQLOrderByTerm@2
            //
        }
    }

    @Test
    public void test4() throws Throwable {
        YSQLConstant ySQLConstant0 = YSQLConstant.createNullConstant();
        YSQLOrderByTerm.YSQLOrder ySQLOrderByTerm_YSQLOrder0 = YSQLOrderByTerm.YSQLOrder.ASC;
        YSQLOrderByTerm ySQLOrderByTerm0 = new YSQLOrderByTerm(ySQLConstant0, ySQLOrderByTerm_YSQLOrder0);
        ySQLOrderByTerm0.getExpressionType();
    }

    @Test
    public void test5() throws Throwable {
        YSQLConstant.YSQLNullConstant ySQLConstant_YSQLNullConstant0 = new YSQLConstant.YSQLNullConstant();
        YSQLOrderByTerm ySQLOrderByTerm0 = new YSQLOrderByTerm(ySQLConstant_YSQLNullConstant0,
                (YSQLOrderByTerm.YSQLOrder) null);
        ySQLOrderByTerm0.getOrder();
    }

    @Test
    public void test6() throws Throwable {
        YSQLConstant ySQLConstant0 = YSQLConstant.createNullConstant();
        YSQLOrderByTerm.YSQLOrder ySQLOrderByTerm_YSQLOrder0 = YSQLOrderByTerm.YSQLOrder.DESC;
        YSQLOrderByTerm ySQLOrderByTerm0 = new YSQLOrderByTerm(ySQLConstant0, ySQLOrderByTerm_YSQLOrder0);
        YSQLExpression ySQLExpression0 = ySQLOrderByTerm0.getExpr();
        assertSame(ySQLConstant0, ySQLExpression0);
    }
}
