/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 07 13:02:33 GMT 2025
 */

package sqlancer.evosuite.yugabyte.ysql.ast;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;

import org.junit.jupiter.api.Test;

import sqlancer.yugabyte.ysql.YSQLSchema;
import sqlancer.yugabyte.ysql.ast.YSQLColumnValue;
import sqlancer.yugabyte.ysql.ast.YSQLConstant;

public class YSQLColumnValue_ESTest {

    @Test
    public void test0() throws Throwable {
        YSQLSchema.YSQLColumn ySQLSchema_YSQLColumn0 = YSQLSchema.YSQLColumn.createDummy("5aDX{,A}DqVp5");
        YSQLColumnValue ySQLColumnValue0 = new YSQLColumnValue(ySQLSchema_YSQLColumn0, (YSQLConstant) null);
        YSQLSchema.YSQLDataType ySQLSchema_YSQLDataType0 = ySQLColumnValue0.getExpressionType();
        assertEquals(YSQLSchema.YSQLDataType.INT, ySQLSchema_YSQLDataType0);
    }

    @Test
    public void test1() throws Throwable {
        YSQLSchema.YSQLColumn ySQLSchema_YSQLColumn0 = YSQLSchema.YSQLColumn.createDummy("5aDX{,A}DqVp5");
        YSQLColumnValue ySQLColumnValue0 = new YSQLColumnValue(ySQLSchema_YSQLColumn0, (YSQLConstant) null);
        YSQLConstant ySQLConstant0 = ySQLColumnValue0.getExpectedValue();
        assertNull(ySQLConstant0);
    }

    @Test
    public void test2() throws Throwable {
        YSQLSchema.YSQLColumn ySQLSchema_YSQLColumn0 = YSQLSchema.YSQLColumn.createDummy("}b1(!ImHd|E8W9prnc");
        YSQLConstant ySQLConstant0 = YSQLConstant.createByteConstant("}b1(!ImHd|E8W9prnc: INT");
        YSQLColumnValue ySQLColumnValue0 = YSQLColumnValue.create(ySQLSchema_YSQLColumn0, ySQLConstant0);
        YSQLConstant ySQLConstant1 = ySQLColumnValue0.getExpectedValue();
        assertSame(ySQLConstant0, ySQLConstant1);
    }

    @Test
    public void test3() throws Throwable {
        YSQLSchema.YSQLDataType ySQLSchema_YSQLDataType0 = YSQLSchema.YSQLDataType.BIT;
        YSQLSchema.YSQLColumn ySQLSchema_YSQLColumn0 = new YSQLSchema.YSQLColumn("", ySQLSchema_YSQLDataType0);
        YSQLConstant ySQLConstant0 = YSQLConstant.createIntConstant((-2482L));
        YSQLColumnValue ySQLColumnValue0 = new YSQLColumnValue(ySQLSchema_YSQLColumn0, ySQLConstant0);
        YSQLConstant ySQLConstant1 = ySQLColumnValue0.getExpectedValue();
        assertTrue(ySQLConstant1.isInt());
    }

    @Test
    public void test4() throws Throwable {
        YSQLSchema.YSQLColumn ySQLSchema_YSQLColumn0 = YSQLSchema.YSQLColumn.createDummy("5aDX{,A}DqVp5");
        YSQLConstant.BooleanConstant ySQLConstant_BooleanConstant0 = new YSQLConstant.BooleanConstant(true);
        YSQLColumnValue ySQLColumnValue0 = YSQLColumnValue.create(ySQLSchema_YSQLColumn0,
                ySQLConstant_BooleanConstant0);
        YSQLConstant ySQLConstant0 = ySQLColumnValue0.getExpectedValue();
        assertEquals("TRUE", ySQLConstant0.getUnquotedTextRepresentation());
    }

    @Test
    public void test5() throws Throwable {
        YSQLSchema.YSQLDataType ySQLSchema_YSQLDataType0 = YSQLSchema.YSQLDataType.BIT;
        YSQLSchema.YSQLColumn ySQLSchema_YSQLColumn0 = new YSQLSchema.YSQLColumn("", ySQLSchema_YSQLDataType0);
        YSQLConstant ySQLConstant0 = YSQLConstant.createIntConstant((-2482L));
        YSQLColumnValue ySQLColumnValue0 = new YSQLColumnValue(ySQLSchema_YSQLColumn0, ySQLConstant0);
        YSQLSchema.YSQLColumn ySQLSchema_YSQLColumn1 = ySQLColumnValue0.getColumn();
        assertSame(ySQLSchema_YSQLColumn0, ySQLSchema_YSQLColumn1);
    }

    @Test
    public void test6() throws Throwable {
        YSQLConstant ySQLConstant0 = YSQLConstant.createTrue();
        YSQLColumnValue ySQLColumnValue0 = YSQLColumnValue.create((YSQLSchema.YSQLColumn) null, ySQLConstant0);
        // Undeclared exception!
        try {
            ySQLColumnValue0.getExpressionType();
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("sqlancer.yugabyte.ysql.ast.YSQLColumnValue", e);
        }
    }

    private void verifyException(String s, NullPointerException e) {
    }

    @Test
    public void test7() throws Throwable {
        YSQLConstant ySQLConstant0 = YSQLConstant.createTrue();
        YSQLColumnValue ySQLColumnValue0 = YSQLColumnValue.create((YSQLSchema.YSQLColumn) null, ySQLConstant0);
        YSQLSchema.YSQLColumn ySQLSchema_YSQLColumn0 = ySQLColumnValue0.getColumn();
        assertNull(ySQLSchema_YSQLColumn0);
    }

    @Test
    public void test8() throws Throwable {
        YSQLSchema.YSQLDataType ySQLSchema_YSQLDataType0 = YSQLSchema.YSQLDataType.BYTEA;
        YSQLSchema.YSQLColumn ySQLSchema_YSQLColumn0 = new YSQLSchema.YSQLColumn("", ySQLSchema_YSQLDataType0);
        YSQLConstant ySQLConstant0 = YSQLConstant.createNullConstant();
        YSQLColumnValue ySQLColumnValue0 = YSQLColumnValue.create(ySQLSchema_YSQLColumn0, ySQLConstant0);
        YSQLConstant ySQLConstant1 = ySQLColumnValue0.getExpectedValue();
        assertFalse(ySQLConstant1.isString());
    }

    @Test
    public void test9() throws Throwable {
        YSQLConstant.YSQLNullConstant ySQLConstant_YSQLNullConstant0 = new YSQLConstant.YSQLNullConstant();
        YSQLSchema.YSQLColumn ySQLSchema_YSQLColumn0 = new YSQLSchema.YSQLColumn((String) null,
                (YSQLSchema.YSQLDataType) null);
        YSQLColumnValue ySQLColumnValue0 = YSQLColumnValue.create(ySQLSchema_YSQLColumn0,
                ySQLConstant_YSQLNullConstant0);
        ySQLColumnValue0.getExpressionType();
    }
}
