/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Apr 07 13:10:31 GMT 2025
 */

package sqlancer.questdb.ast;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class QuestDBInOperation_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "sqlancer.questdb.ast.QuestDBInOperation"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\yewjo\\OneDrive\\Desktop\\NUS\\y4s2\\cs3213\\project\\sqlancer"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\yewjo\\AppData\\Local\\Temp\\"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(QuestDBInOperation_ESTest_scaffolding.class.getClassLoader() ,
      "sqlancer.common.ast.newast.NewInOperatorNode",
      "sqlancer.questdb.ast.QuestDBExpression",
      "sqlancer.questdb.ast.QuestDBInOperation",
      "sqlancer.questdb.ast.QuestDBConstant$QuestDBBooleanConstant",
      "sqlancer.common.ast.SelectBase",
      "sqlancer.common.ast.SelectBase$SelectType",
      "sqlancer.questdb.ast.QuestDBConstant$QuestDBIntConstant",
      "sqlancer.common.ast.newast.Expression",
      "sqlancer.questdb.ast.QuestDBSelect",
      "sqlancer.questdb.ast.QuestDBConstant",
      "sqlancer.questdb.ast.QuestDBConstant$QuestDBDoubleConstant"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(QuestDBInOperation_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "sqlancer.common.ast.newast.NewInOperatorNode",
      "sqlancer.questdb.ast.QuestDBInOperation",
      "sqlancer.questdb.ast.QuestDBConstant",
      "sqlancer.questdb.ast.QuestDBConstant$QuestDBIntConstant",
      "sqlancer.Randomly$StringGenerationStrategy$4",
      "sqlancer.Randomly$StringGenerationStrategy",
      "sqlancer.Randomly",
      "sqlancer.questdb.ast.QuestDBConstant$QuestDBDoubleConstant",
      "sqlancer.common.ast.SelectBase",
      "sqlancer.questdb.ast.QuestDBSelect",
      "sqlancer.questdb.ast.QuestDBConstant$QuestDBSymbolConstant",
      "sqlancer.questdb.ast.QuestDBConstant$QuestDBBooleanConstant",
      "sqlancer.postgres.ast.PostgresBinaryComparisonOperation$PostgresBinaryComparisonOperator",
      "sqlancer.common.ast.newast.NewBinaryOperatorNode",
      "sqlancer.questdb.ast.QuestDBBinaryOperation",
      "sqlancer.questdb.QuestDBSchema$QuestDBCompositeDataType",
      "sqlancer.common.schema.AbstractTableColumn",
      "sqlancer.questdb.QuestDBSchema$QuestDBColumn",
      "sqlancer.common.ast.newast.ColumnReferenceNode",
      "sqlancer.questdb.ast.QuestDBColumnReference",
      "sqlancer.oceanbase.ast.OceanBaseUnaryPrefixOperation$OceanBaseUnaryPrefixOperator",
      "sqlancer.doris.ast.DorisBinaryLogicalOperation$DorisBinaryLogicalOperator",
      "sqlancer.doris.ast.DorisBinaryComparisonOperation$DorisBinaryComparisonOperator",
      "sqlancer.common.ast.newast.NewUnaryPostfixOperatorNode",
      "sqlancer.questdb.ast.QuestDBUnaryPostfixOperation",
      "sqlancer.questdb.ast.QuestDBConstant$QuestDBNullConstant",
      "sqlancer.materialize.MaterializeSchema$MaterializeDataType",
      "sqlancer.materialize.ast.MaterializePrefixOperation$PrefixOperator",
      "sqlancer.clickhouse.ast.ClickHouseUnaryPrefixOperation$ClickHouseUnaryPrefixOperator",
      "sqlancer.common.ast.newast.NewUnaryPrefixOperatorNode",
      "sqlancer.questdb.ast.QuestDBUnaryPrefixOperation",
      "sqlancer.postgres.ast.PostgresBinaryBitOperation$PostgresBinaryBitOperator",
      "sqlancer.doris.ast.DorisLikeOperation$DorisLikeOperator",
      "sqlancer.materialize.ast.MaterializePostfixOperation$PostfixOperator",
      "sqlancer.tidb.ast.TiDBBinaryArithmeticOperation$TiDBBinaryArithmeticOperator",
      "sqlancer.common.ast.SelectBase$SelectType"
    );
  }
}
