/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 07 13:10:31 GMT 2025
 */

package sqlancer.questdb.ast;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sqlancer.questdb.ast.QuestDBConstant;
import sqlancer.questdb.ast.QuestDBExpression;
import sqlancer.questdb.ast.QuestDBInOperation;
import sqlancer.questdb.ast.QuestDBSelect;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class QuestDBInOperation_ESTest extends QuestDBInOperation_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      QuestDBExpression questDBExpression0 = QuestDBConstant.createBooleanConstant(true);
      QuestDBSelect questDBSelect0 = new QuestDBSelect();
      List<QuestDBExpression> list0 = questDBSelect0.getGroupByExpressions();
      QuestDBInOperation questDBInOperation0 = new QuestDBInOperation(questDBExpression0, list0, true);
      assertTrue(questDBInOperation0.isNegated());
  }
}
