/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 07 12:58:49 GMT 2025
 */

package sqlancer.questdb.ast;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sqlancer.materialize.ast.MaterializePostfixOperation;
import sqlancer.questdb.ast.QuestDBConstant;
import sqlancer.questdb.ast.QuestDBUnaryPostfixOperation;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class QuestDBUnaryPostfixOperation_ESTest extends QuestDBUnaryPostfixOperation_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      QuestDBConstant.QuestDBIntConstant questDBConstant_QuestDBIntConstant0 = new QuestDBConstant.QuestDBIntConstant(430L);
      MaterializePostfixOperation.PostfixOperator materializePostfixOperation_PostfixOperator0 = MaterializePostfixOperation.PostfixOperator.getRandom();
      QuestDBUnaryPostfixOperation questDBUnaryPostfixOperation0 = new QuestDBUnaryPostfixOperation(questDBConstant_QuestDBIntConstant0, materializePostfixOperation_PostfixOperator0);
  }
}
