/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 07 13:28:03 GMT 2025
 */

package sqlancer.doris.ast;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sqlancer.common.ast.newast.NewOrderingTerm;
import sqlancer.doris.ast.DorisExpression;
import sqlancer.doris.ast.DorisOrderByTerm;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DorisOrderByTerm_ESTest extends DorisOrderByTerm_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NewOrderingTerm.Ordering newOrderingTerm_Ordering0 = NewOrderingTerm.Ordering.ASC;
      DorisOrderByTerm dorisOrderByTerm0 = new DorisOrderByTerm((DorisExpression) null, newOrderingTerm_Ordering0);
      assertEquals(NewOrderingTerm.Ordering.ASC, dorisOrderByTerm0.getOrdering());
  }
}
