/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Apr 07 12:56:25 GMT 2025
 */

package sqlancer.doris.ast;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class DorisInOperation_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "sqlancer.doris.ast.DorisInOperation"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\yewjo\\OneDrive\\Desktop\\NUS\\y4s2\\cs3213\\project\\sqlancer"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\yewjo\\AppData\\Local\\Temp\\"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(DorisInOperation_ESTest_scaffolding.class.getClassLoader() ,
      "sqlancer.doris.DorisSchema$DorisColumnAggrType",
      "sqlancer.common.ast.newast.ColumnReferenceNode",
      "sqlancer.doris.ast.DorisConstant$DorisDatetimeConstant",
      "sqlancer.doris.DorisSchema$DorisDataType",
      "sqlancer.Randomly",
      "sqlancer.doris.ast.DorisInOperation",
      "sqlancer.doris.ast.DorisConstant$DorisIntConstant",
      "sqlancer.DatabendDorisPrestoConstant",
      "sqlancer.doris.ast.DorisConstant$DorisNumericConstant",
      "sqlancer.common.ast.BinaryNode",
      "sqlancer.common.ast.BinaryOperatorNode",
      "sqlancer.doris.ast.DorisBinaryArithmeticOperation",
      "sqlancer.common.visitor.BinaryOperation",
      "sqlancer.SQLProviderAdapter",
      "sqlancer.doris.ast.DorisBinaryArithmeticOperation$DorisBinaryArithmeticOperator",
      "sqlancer.common.schema.AbstractTableColumn",
      "sqlancer.Randomly$StringGenerationStrategy",
      "sqlancer.doris.utils.DorisNumberUtils",
      "sqlancer.materialize.MaterializeSchema",
      "sqlancer.doris.ast.DorisConstant$DorisTextConstant",
      "sqlancer.common.ast.newast.Expression",
      "sqlancer.doris.DorisSchema$DorisColumn",
      "sqlancer.doris.ast.DorisConstant$DorisFloatConstant",
      "sqlancer.common.ast.BinaryOperatorNode$Operator",
      "sqlancer.Randomly$StringGenerationStrategy$4",
      "sqlancer.Randomly$StringGenerationStrategy$3",
      "sqlancer.common.schema.AbstractTable",
      "sqlancer.Randomly$StringGenerationStrategy$2",
      "sqlancer.doris.DorisProvider",
      "sqlancer.common.ast.newast.NewBinaryOperatorNode",
      "sqlancer.Randomly$StringGenerationStrategy$1",
      "sqlancer.materialize.ast.MaterializeBinaryBitOperation$MaterializeBinaryBitOperator",
      "sqlancer.doris.ast.DorisConstant$DorisBooleanConstant",
      "sqlancer.doris.ast.DorisExpression",
      "sqlancer.common.schema.AbstractSchema",
      "sqlancer.doris.ast.DorisConstant$DorisDateConstant",
      "sqlancer.doris.DorisSchema$DorisCompositeDataType",
      "sqlancer.DatabaseProvider",
      "sqlancer.doris.ast.DorisColumnValue",
      "sqlancer.common.ast.newast.NewInOperatorNode",
      "sqlancer.doris.ast.DorisConstant$DorisTemporalConstant",
      "sqlancer.materialize.ast.MaterializeBinaryBitOperation",
      "sqlancer.IgnoreMeException",
      "sqlancer.ProviderAdapter",
      "sqlancer.materialize.ast.MaterializeExpression",
      "sqlancer.doris.DorisSchema",
      "sqlancer.doris.ast.DorisConstant$DorisNullConstant",
      "sqlancer.doris.ast.DorisConstant"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(DorisInOperation_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "sqlancer.common.ast.newast.NewInOperatorNode",
      "sqlancer.doris.ast.DorisInOperation",
      "sqlancer.doris.DorisSchema$DorisDataType",
      "sqlancer.DatabendDorisPrestoConstant",
      "sqlancer.doris.ast.DorisConstant",
      "sqlancer.doris.ast.DorisConstant$DorisTextConstant",
      "sqlancer.doris.ast.DorisConstant$DorisTemporalConstant",
      "sqlancer.doris.ast.DorisConstant$DorisDateConstant",
      "sqlancer.doris.utils.DorisNumberUtils",
      "sqlancer.doris.ast.DorisConstant$DorisBooleanConstant",
      "sqlancer.common.ast.SelectBase",
      "sqlancer.doris.ast.DorisSelect",
      "sqlancer.doris.ast.DorisSelect$DorisSelectDistinctType",
      "sqlancer.doris.ast.DorisCaseOperation",
      "sqlancer.doris.ast.DorisConstant$DorisNullConstant",
      "sqlancer.materialize.MaterializeSchema$MaterializeDataType",
      "sqlancer.materialize.ast.MaterializePrefixOperation$PrefixOperator",
      "sqlancer.common.ast.newast.NewBinaryOperatorNode",
      "sqlancer.doris.ast.DorisBinaryArithmeticOperation",
      "sqlancer.GlobalState",
      "sqlancer.SQLGlobalState",
      "sqlancer.doris.DorisProvider$DorisGlobalState",
      "sqlancer.common.gen.TypedExpressionGenerator",
      "sqlancer.doris.gen.DorisNewExpressionGenerator",
      "sqlancer.common.ast.newast.NewUnaryPrefixOperatorNode",
      "sqlancer.doris.ast.DorisUnaryPrefixOperation",
      "sqlancer.doris.ast.DorisCastOperation",
      "sqlancer.LikeImplementationHelper",
      "sqlancer.doris.ast.DorisConstant$DorisDatetimeConstant",
      "sqlancer.Randomly$StringGenerationStrategy$4",
      "sqlancer.Randomly$StringGenerationStrategy",
      "sqlancer.Randomly",
      "sqlancer.doris.ast.DorisConstant$DorisNumericConstant",
      "sqlancer.doris.ast.DorisConstant$DorisFloatConstant",
      "sqlancer.common.schema.AbstractTable",
      "sqlancer.common.schema.AbstractRelationalTable",
      "sqlancer.doris.DorisSchema$DorisTable",
      "sqlancer.doris.DorisSchema$DorisCompositeDataType",
      "sqlancer.common.schema.AbstractTableColumn",
      "sqlancer.doris.DorisSchema$DorisColumn",
      "sqlancer.databend.ast.DatabendBinaryComparisonOperation$DatabendBinaryComparisonOperator",
      "sqlancer.doris.ast.DorisBinaryOperation",
      "sqlancer.common.ast.newast.NewFunctionNode",
      "sqlancer.doris.ast.DorisFunction",
      "sqlancer.doris.ast.DorisAggregateOperation",
      "sqlancer.common.ast.JoinBase",
      "sqlancer.doris.ast.DorisJoin",
      "sqlancer.common.ast.JoinBase$JoinType",
      "sqlancer.doris.ast.DorisBinaryComparisonOperation",
      "sqlancer.common.ast.newast.ColumnReferenceNode",
      "sqlancer.doris.ast.DorisColumnReference",
      "sqlancer.common.ast.newast.NewBetweenOperatorNode",
      "sqlancer.doris.ast.DorisBetweenOperation",
      "sqlancer.doris.ast.DorisBinaryLogicalOperation",
      "sqlancer.doris.ast.DorisConstant$DorisIntConstant",
      "sqlancer.common.ast.newast.TableReferenceNode",
      "sqlancer.doris.ast.DorisTableReference",
      "sqlancer.common.query.ExpectedErrors",
      "sqlancer.common.query.Query",
      "sqlancer.common.query.SQLQueryAdapter",
      "sqlancer.materialize.ast.MaterializeBinaryRangeOperation$MaterializeBinaryRangeOperator",
      "sqlancer.common.ast.newast.NewPostfixTextNode",
      "sqlancer.doris.ast.DorisPostfixText",
      "sqlancer.postgres.ast.PostgresBinaryComparisonOperation$PostgresBinaryComparisonOperator",
      "sqlancer.common.ast.newast.NewUnaryPostfixOperatorNode",
      "sqlancer.doris.ast.DorisUnaryPostfixOperation",
      "sqlancer.common.ast.newast.NewOrderingTerm",
      "sqlancer.doris.ast.DorisOrderByTerm",
      "sqlancer.doris.ast.DorisColumnValue",
      "sqlancer.cockroachdb.ast.CockroachDBBinaryLogicalOperation$CockroachDBBinaryLogicalOperator",
      "sqlancer.doris.ast.DorisFunctionOperation",
      "sqlancer.tidb.ast.TiDBBinaryBitOperation$TiDBBinaryBitOperator",
      "sqlancer.mysql.ast.MySQLUnaryPrefixOperation$MySQLUnaryPrefixOperator",
      "sqlancer.tidb.ast.TiDBBinaryArithmeticOperation$TiDBBinaryArithmeticOperator",
      "sqlancer.common.ast.newast.NewAliasNode",
      "sqlancer.doris.ast.DorisAlias",
      "sqlancer.doris.ast.DorisLikeOperation",
      "sqlancer.common.ast.newast.NewToStringVisitor",
      "sqlancer.doris.visitor.DorisToStringVisitor",
      "sqlancer.clickhouse.ast.ClickHouseUnaryFunctionOperation$ClickHouseUnaryFunctionOperator",
      "sqlancer.cockroachdb.ast.CockroachDBUnaryPostfixOperation$CockroachDBUnaryPostfixOperator",
      "sqlancer.hsqldb.ast.HSQLDBUnaryPostfixOperation$HSQLDBUnaryPostfixOperator",
      "sqlancer.common.query.SQLQueryResultCheckAdapter",
      "sqlancer.databend.ast.DatabendUnaryPostfixOperation$DatabendUnaryPostfixOperator",
      "sqlancer.hsqldb.HSQLDBSchema$HSQLDBDataType",
      "sqlancer.hsqldb.ast.HSQLDBUnaryPrefixOperation$HSQLDBUnaryPrefixOperator",
      "sqlancer.databend.DatabendSchema$DatabendDataType",
      "sqlancer.databend.ast.DatabendUnaryPrefixOperation$DatabendUnaryPrefixOperator",
      "sqlancer.cnosdb.ast.CnosDBPostfixOperation$PostfixOperator",
      "sqlancer.postgres.ast.PostgresBinaryArithmeticOperation$PostgresBinaryOperator",
      "sqlancer.postgres.ast.PostgresBinaryRangeOperation$PostgresBinaryRangeOperator",
      "sqlancer.oceanbase.OceanBaseGlobalState",
      "sqlancer.tidb.ast.TiDBUnaryPrefixOperation$TiDBUnaryPrefixOperator",
      "sqlancer.postgres.ast.PostgresPOSIXRegularExpression$POSIXRegex",
      "sqlancer.common.schema.AbstractRowValue",
      "sqlancer.doris.DorisSchema$DorisRowValue",
      "sqlancer.common.schema.AbstractTables",
      "sqlancer.postgres.PostgresSchema$PostgresDataType",
      "sqlancer.postgres.ast.PostgresPrefixOperation$PrefixOperator",
      "sqlancer.postgres.ast.PostgresBinaryBitOperation$PostgresBinaryBitOperator",
      "sqlancer.h2.H2ExpressionGenerator$H2BinaryLogicalOperator",
      "sqlancer.databend.ast.DatabendLikeOperation$DatabendLikeOperator",
      "sqlancer.h2.H2ExpressionGenerator$H2UnaryPostfixOperator",
      "sqlancer.materialize.ast.MaterializeBinaryBitOperation$MaterializeBinaryBitOperator",
      "sqlancer.materialize.ast.MaterializePostfixOperation$PostfixOperator",
      "sqlancer.postgres.ast.PostgresPostfixOperation$PostfixOperator",
      "sqlancer.cnosdb.ast.CnosDBBinaryArithmeticOperation$CnosDBBinaryOperator",
      "sqlancer.materialize.ast.MaterializeBinaryArithmeticOperation$MaterializeBinaryOperator",
      "sqlancer.oceanbase.ast.OceanBaseUnaryPrefixOperation$OceanBaseUnaryPrefixOperator",
      "sqlancer.tidb.ast.TiDBRegexOperation$TiDBRegexOperator",
      "sqlancer.h2.H2ExpressionGenerator$H2BinaryComparisonOperator",
      "sqlancer.ExpandedGlobalState",
      "sqlancer.postgres.PostgresGlobalState",
      "sqlancer.cnosdb.ast.CnosDBBinaryComparisonOperation$CnosDBBinaryComparisonOperator",
      "sqlancer.materialize.ast.MaterializePOSIXRegularExpression$POSIXRegex",
      "sqlancer.common.schema.TableIndex",
      "sqlancer.oceanbase.OceanBaseSchema$OceanBaseIndex",
      "sqlancer.oceanbase.OceanBaseSchema$OceanBaseTable",
      "sqlancer.materialize.ast.MaterializeBinaryComparisonOperation$MaterializeBinaryComparisonOperator",
      "sqlancer.doris.DorisSchema$DorisColumnAggrType"
    );
  }
}
