/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Apr 07 13:45:40 GMT 2025
 */

package sqlancer.tidb.ast;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class TiDBBinaryComparisonOperation_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "sqlancer.tidb.ast.TiDBBinaryComparisonOperation"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\yewjo\\OneDrive\\Desktop\\NUS\\y4s2\\cs3213\\project\\sqlancer"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\yewjo\\AppData\\Local\\Temp\\"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(TiDBBinaryComparisonOperation_ESTest_scaffolding.class.getClassLoader() ,
      "sqlancer.Randomly",
      "sqlancer.tidb.ast.TiDBBinaryComparisonOperation",
      "sqlancer.common.ast.BinaryNode",
      "sqlancer.common.ast.BinaryOperatorNode",
      "sqlancer.common.visitor.BinaryOperation",
      "sqlancer.tidb.ast.TiDBJoin",
      "sqlancer.common.ast.JoinBase$JoinType",
      "sqlancer.Randomly$StringGenerationStrategy",
      "sqlancer.common.ast.SelectBase$SelectType",
      "sqlancer.common.ast.newast.Expression",
      "sqlancer.SQLGlobalState",
      "sqlancer.common.ast.BinaryOperatorNode$Operator",
      "sqlancer.Randomly$StringGenerationStrategy$4",
      "sqlancer.Randomly$StringGenerationStrategy$3",
      "sqlancer.Randomly$StringGenerationStrategy$2",
      "sqlancer.Randomly$StringGenerationStrategy$1",
      "sqlancer.GlobalState",
      "sqlancer.common.ast.newast.Select",
      "sqlancer.tidb.ast.TiDBSelect",
      "sqlancer.tidb.ast.TiDBBinaryComparisonOperation$TiDBComparisonOperator",
      "sqlancer.common.ast.newast.Join",
      "sqlancer.tidb.ast.TiDBExpression",
      "sqlancer.tidb.TiDBProvider$TiDBGlobalState",
      "sqlancer.IgnoreMeException",
      "sqlancer.common.ast.SelectBase",
      "sqlancer.tidb.ast.TiDBJoin$NaturalJoinType",
      "sqlancer.common.ast.JoinBase"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(TiDBBinaryComparisonOperation_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "sqlancer.common.ast.BinaryNode",
      "sqlancer.common.ast.BinaryOperatorNode",
      "sqlancer.tidb.ast.TiDBBinaryComparisonOperation",
      "sqlancer.tidb.ast.TiDBBinaryComparisonOperation$TiDBComparisonOperator",
      "sqlancer.common.ast.JoinBase",
      "sqlancer.tidb.ast.TiDBJoin",
      "sqlancer.Randomly$StringGenerationStrategy$4",
      "sqlancer.Randomly$StringGenerationStrategy",
      "sqlancer.Randomly",
      "sqlancer.common.ast.SelectBase",
      "sqlancer.tidb.ast.TiDBSelect",
      "sqlancer.tidb.TiDBSchema$TiDBCompositeDataType",
      "sqlancer.tidb.TiDBSchema$TiDBDataType",
      "sqlancer.common.schema.AbstractTableColumn",
      "sqlancer.tidb.TiDBSchema$TiDBColumn",
      "sqlancer.tidb.ast.TiDBColumnReference",
      "sqlancer.tidb.ast.TiDBConstant",
      "sqlancer.tidb.ast.TiDBConstant$TiDBBooleanConstant",
      "sqlancer.tidb.ast.TiDBConstant$TiDBIntConstant",
      "sqlancer.tidb.ast.TiDBConstant$TiDBTextConstant",
      "sqlancer.tidb.ast.TiDBConstant$TiDBDoubleConstant",
      "sqlancer.SQLConstantUtils",
      "sqlancer.tidb.ast.TiDBBinaryLogicalOperation",
      "sqlancer.tidb.ast.TiDBRegexOperation",
      "sqlancer.tidb.ast.TiDBOrderingTerm",
      "sqlancer.tidb.ast.TiDBText",
      "sqlancer.tidb.ast.TiDBConstant$TiDBNullConstant",
      "sqlancer.common.ast.UnaryNode",
      "sqlancer.tidb.ast.TiDBCollate",
      "sqlancer.tidb.ast.TiDBFunctionCall",
      "sqlancer.common.ast.UnaryOperatorNode",
      "sqlancer.tidb.ast.TiDBUnaryPrefixOperation",
      "sqlancer.GlobalState",
      "sqlancer.SQLGlobalState",
      "sqlancer.tidb.TiDBProvider$TiDBGlobalState",
      "sqlancer.tidb.ast.TiDBBinaryArithmeticOperation",
      "sqlancer.tidb.ast.TiDBBinaryBitOperation",
      "sqlancer.tidb.ast.TiDBConstant$TiDBBitConstant",
      "sqlancer.common.ast.FunctionNode",
      "sqlancer.tidb.ast.TiDBAggregate",
      "sqlancer.tidb.ast.TiDBCastOperation",
      "sqlancer.databend.ast.DatabendSelect",
      "sqlancer.cockroachdb.ast.CockroachDBBinaryArithmeticOperation$CockroachDBBinaryArithmeticOperator",
      "sqlancer.common.ast.newast.NewBinaryOperatorNode",
      "sqlancer.databend.ast.DatabendBinaryArithmeticOperation",
      "sqlancer.databend.ast.DatabendBinaryLogicalOperation",
      "sqlancer.cnosdb.ast.CnosDBBinaryComparisonOperation$CnosDBBinaryComparisonOperator",
      "sqlancer.databend.ast.DatabendBinaryOperation",
      "sqlancer.tidb.ast.TiDBCase",
      "sqlancer.tidb.ast.TiDBUnaryPostfixOperation",
      "sqlancer.common.schema.AbstractTable",
      "sqlancer.common.schema.AbstractRelationalTable",
      "sqlancer.tidb.TiDBSchema$TiDBTable",
      "sqlancer.tidb.ast.TiDBTableReference",
      "sqlancer.common.visitor.NodeVisitor",
      "sqlancer.common.visitor.ToStringVisitor",
      "sqlancer.tidb.visitor.TiDBToStringVisitor",
      "sqlancer.common.schema.TableIndex",
      "sqlancer.common.query.Query",
      "sqlancer.common.query.SQLQueryAdapter",
      "sqlancer.common.query.ExpectedErrors",
      "sqlancer.databend.DatabendSchema$DatabendCompositeDataType",
      "sqlancer.databend.DatabendSchema$DatabendColumn",
      "sqlancer.common.ast.newast.NewFunctionNode",
      "sqlancer.datafusion.ast.DataFusionFunction",
      "sqlancer.common.ast.SelectBase$SelectType",
      "sqlancer.common.ast.JoinBase$JoinType"
    );
  }
}
