/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Apr 07 14:26:55 GMT 2025
 */

package sqlancer.mariadb.ast;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class MariaDBFunction_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "sqlancer.mariadb.ast.MariaDBFunction"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\yewjo\\OneDrive\\Desktop\\NUS\\y4s2\\cs3213\\project\\sqlancer"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\yewjo\\AppData\\Local\\Temp\\"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(MariaDBFunction_ESTest_scaffolding.class.getClassLoader() ,
      "sqlancer.MainOptions",
      "sqlancer.common.ast.newast.Select",
      "sqlancer.mariadb.ast.MariaDBConstant",
      "sqlancer.mariadb.ast.MariaDBConstant$MariaDBDoubleConstant",
      "sqlancer.Randomly",
      "sqlancer.common.schema.AbstractSchema",
      "sqlancer.mariadb.ast.MariaDBFunctionName$FunctionAttribute",
      "sqlancer.mariadb.ast.MariaDBFunction",
      "sqlancer.mariadb.ast.MariaDBFunctionName",
      "sqlancer.mariadb.ast.MariaDBExpression",
      "sqlancer.mariadb.MariaDBSchema",
      "sqlancer.Randomly$StringGenerationStrategy",
      "sqlancer.mariadb.ast.MariaDBSelectStatement",
      "sqlancer.mariadb.ast.MariaDBConstant$MariaDBBooleanConstant",
      "sqlancer.IgnoreMeException",
      "sqlancer.common.ast.SelectBase",
      "sqlancer.common.ast.SelectBase$SelectType",
      "sqlancer.common.ast.newast.Expression",
      "sqlancer.mariadb.ast.MariaDBSelectStatement$MariaDBSelectType",
      "sqlancer.Randomly$StringGenerationStrategy$4",
      "sqlancer.Randomly$StringGenerationStrategy$3",
      "sqlancer.Randomly$StringGenerationStrategy$2",
      "sqlancer.mariadb.ast.MariaDBConstant$MariaDBIntConstant",
      "sqlancer.Randomly$StringGenerationStrategy$1"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(MariaDBFunction_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "sqlancer.mariadb.ast.MariaDBFunction",
      "sqlancer.common.ast.SelectBase",
      "sqlancer.mariadb.ast.MariaDBSelectStatement",
      "sqlancer.mariadb.ast.MariaDBBinaryOperator",
      "sqlancer.cockroachdb.CockroachDBSchema$CockroachDBCompositeDataType",
      "sqlancer.Randomly$StringGenerationStrategy$4",
      "sqlancer.Randomly$StringGenerationStrategy",
      "sqlancer.Randomly",
      "sqlancer.common.schema.AbstractTableColumn",
      "sqlancer.mariadb.MariaDBSchema$MariaDBColumn",
      "sqlancer.mariadb.ast.MariaDBColumnName",
      "sqlancer.mariadb.ast.MariaDBConstant",
      "sqlancer.mariadb.ast.MariaDBConstant$MariaDBIntConstant",
      "sqlancer.mariadb.ast.MariaDBPostfixUnaryOperation",
      "sqlancer.common.visitor.NodeVisitor",
      "sqlancer.common.visitor.ToStringVisitor",
      "sqlancer.mariadb.ast.MariaDBStringVisitor",
      "sqlancer.mariadb.ast.MariaDBConstant$MariaDBNullConstant",
      "sqlancer.mariadb.ast.MariaDBInOperation",
      "sqlancer.mariadb.ast.MariaDBConstant$MariaDBTextConstant",
      "sqlancer.mariadb.ast.MariaDBConstant$MariaDBDoubleConstant",
      "sqlancer.mariadb.ast.MariaDBConstant$MariaDBBooleanConstant",
      "sqlancer.common.schema.AbstractTable",
      "sqlancer.common.schema.AbstractRelationalTable",
      "sqlancer.mariadb.MariaDBSchema$MariaDBTable",
      "sqlancer.common.ast.JoinBase",
      "sqlancer.mariadb.ast.MariaDBJoin",
      "sqlancer.mariadb.ast.MariaDBUnaryPrefixOperation",
      "sqlancer.cockroachdb.CockroachDBSchema$CockroachDBColumn",
      "sqlancer.mariadb.ast.MariaDBAggregate",
      "sqlancer.common.schema.TableIndex",
      "sqlancer.mariadb.MariaDBSchema$MariaDBIndex",
      "sqlancer.mariadb.ast.MariaDBText",
      "sqlancer.mariadb.ast.MariaDBTableReference",
      "sqlancer.databend.DatabendSchema$DatabendCompositeDataType",
      "sqlancer.databend.DatabendSchema$DatabendColumn",
      "sqlancer.materialize.MaterializeSchema$MaterializeColumn",
      "sqlancer.materialize.MaterializeSchema$MaterializeIndex",
      "sqlancer.hsqldb.HSQLDBSchema$HSQLDBTable",
      "sqlancer.sqlite3.schema.SQLite3Schema$SQLite3Table",
      "sqlancer.duckdb.DuckDBSchema$DuckDBCompositeDataType",
      "sqlancer.duckdb.DuckDBSchema$DuckDBColumn",
      "sqlancer.duckdb.DuckDBSchema$DuckDBTable",
      "sqlancer.databend.DatabendSchema$DatabendTable",
      "sqlancer.common.ast.SelectBase$SelectType",
      "sqlancer.mariadb.ast.MariaDBSelectStatement$MariaDBSelectType"
    );
  }
}
