/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 07 13:20:28 GMT 2025
 */

package sqlancer.presto.ast;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sqlancer.presto.ast.PrestoAtTimeZoneOperator;
import sqlancer.presto.ast.PrestoDefaultFunction;
import sqlancer.presto.ast.PrestoExpression;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PrestoAtTimeZoneOperator_ESTest extends PrestoAtTimeZoneOperator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PrestoAtTimeZoneOperator prestoAtTimeZoneOperator0 = new PrestoAtTimeZoneOperator((PrestoExpression) null, (PrestoExpression) null);
      PrestoAtTimeZoneOperator prestoAtTimeZoneOperator1 = new PrestoAtTimeZoneOperator((PrestoExpression) null, prestoAtTimeZoneOperator0);
      PrestoExpression prestoExpression0 = prestoAtTimeZoneOperator1.getTimeZone();
      assertNotSame(prestoAtTimeZoneOperator1, prestoExpression0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PrestoDefaultFunction prestoDefaultFunction0 = PrestoDefaultFunction.GREATEST;
      PrestoAtTimeZoneOperator prestoAtTimeZoneOperator0 = new PrestoAtTimeZoneOperator(prestoDefaultFunction0, prestoDefaultFunction0);
      PrestoExpression prestoExpression0 = prestoAtTimeZoneOperator0.getExpr();
      assertNotNull(prestoExpression0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PrestoAtTimeZoneOperator prestoAtTimeZoneOperator0 = new PrestoAtTimeZoneOperator((PrestoExpression) null, (PrestoExpression) null);
      PrestoExpression prestoExpression0 = prestoAtTimeZoneOperator0.getExpr();
      assertNull(prestoExpression0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PrestoAtTimeZoneOperator prestoAtTimeZoneOperator0 = new PrestoAtTimeZoneOperator((PrestoExpression) null, (PrestoExpression) null);
      PrestoExpression prestoExpression0 = prestoAtTimeZoneOperator0.getTimeZone();
      assertNull(prestoExpression0);
  }
}
