/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 07 14:16:20 GMT 2025
 */

package sqlancer.hsqldb;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sqlancer.hsqldb.HSQLDBOptions;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class HSQLDBOptions_ESTest extends HSQLDBOptions_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HSQLDBOptions hSQLDBOptions0 = null;
      try {
        hSQLDBOptions0 = new HSQLDBOptions();
        fail("Expecting exception: NoSuchMethodError");
      
      } catch(NoSuchMethodError e) {
         //
         // java.util.List.of(Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/List;
         //
         verifyException("sqlancer.hsqldb.HSQLDBOptions", e);
      }
  }
}
