/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 07 13:34:40 GMT 2025
 */

package sqlancer.questdb.test;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sqlancer.questdb.QuestDBProvider;
import sqlancer.questdb.test.QuestDBQueryPartitioningWhereTester;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class QuestDBQueryPartitioningWhereTester_ESTest extends QuestDBQueryPartitioningWhereTester_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      QuestDBProvider.QuestDBGlobalState questDBProvider_QuestDBGlobalState0 = new QuestDBProvider.QuestDBGlobalState();
      QuestDBQueryPartitioningWhereTester questDBQueryPartitioningWhereTester0 = new QuestDBQueryPartitioningWhereTester(questDBProvider_QuestDBGlobalState0);
      // Undeclared exception!
      try { 
        questDBQueryPartitioningWhereTester0.check();
        fail("Expecting exception: AssertionError");
      
      } catch(AssertionError e) {
         //
         // null
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      QuestDBQueryPartitioningWhereTester questDBQueryPartitioningWhereTester0 = new QuestDBQueryPartitioningWhereTester((QuestDBProvider.QuestDBGlobalState) null);
      // Undeclared exception!
      try { 
        questDBQueryPartitioningWhereTester0.check();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sqlancer.questdb.test.QuestDBQueryPartitioningBase", e);
      }
  }
}
