/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 07 13:45:40 GMT 2025
 */

package sqlancer.evosuite.tidb.ast;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

import sqlancer.tidb.ast.TiDBBinaryComparisonOperation;

public class TiDBBinaryComparisonOperation_ESTest {

    @Test
    public void test0() throws Throwable {
        TiDBBinaryComparisonOperation.TiDBComparisonOperator tiDBBinaryComparisonOperation_TiDBComparisonOperator0 = TiDBBinaryComparisonOperation.TiDBComparisonOperator.SMALLER;
        String string0 = tiDBBinaryComparisonOperation_TiDBComparisonOperator0.getTextRepresentation();
        assertEquals("<", string0);
    }

    // @Test
    // public void test1() throws Throwable {
    // TiDBBinaryComparisonOperation.TiDBComparisonOperator tiDBBinaryComparisonOperation_TiDBComparisonOperator0 =
    // TiDBBinaryComparisonOperation.TiDBComparisonOperator
    // .getRandom();
    // TiDBSelect tiDBSelect0 = new TiDBSelect();
    // TiDBJoin tiDBJoin0 = TiDBJoin.createStraightJoin(tiDBSelect0, tiDBSelect0, tiDBSelect0);
    // TiDBBinaryComparisonOperation tiDBBinaryComparisonOperation0 = new TiDBBinaryComparisonOperation(tiDBJoin0,
    // tiDBJoin0, tiDBBinaryComparisonOperation_TiDBComparisonOperator0);
    // assertEquals("=", tiDBBinaryComparisonOperation0.getOperatorRepresentation());
    // }
}
