/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 07 13:08:14 GMT 2025
 */

package sqlancer.evosuite.doris.oracle;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.fail;

import org.junit.jupiter.api.Test;

import sqlancer.common.query.SQLQueryAdapter;
import sqlancer.doris.DorisProvider;
import sqlancer.doris.ast.DorisAlias;
import sqlancer.doris.ast.DorisConstant;
import sqlancer.doris.ast.DorisExpression;
import sqlancer.doris.ast.DorisSelect;
import sqlancer.doris.oracle.DorisPivotedQuerySynthesisOracle;

public class DorisPivotedQuerySynthesisOracle_ESTest {

    @Test
    public void test0() throws Throwable {
        DorisProvider.DorisGlobalState dorisProvider_DorisGlobalState0 = new DorisProvider.DorisGlobalState();
        SQLQueryAdapter sQLQueryAdapter0 = new SQLQueryAdapter("0t?jg=ghD");
        DorisPivotedQuerySynthesisOracle dorisPivotedQuerySynthesisOracle0 = new DorisPivotedQuerySynthesisOracle(
                dorisProvider_DorisGlobalState0);
        try {
            dorisPivotedQuerySynthesisOracle0.getContainmentCheckQuery(sQLQueryAdapter0);
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("sqlancer.doris.oracle.DorisPivotedQuerySynthesisOracle", e);
        }
    }

    @Test
    public void test1() throws Throwable {
        DorisProvider.DorisGlobalState dorisProvider_DorisGlobalState0 = new DorisProvider.DorisGlobalState();
        DorisPivotedQuerySynthesisOracle dorisPivotedQuerySynthesisOracle0 = new DorisPivotedQuerySynthesisOracle(
                dorisProvider_DorisGlobalState0);
        DorisConstant dorisConstant0 = DorisConstant.createStringConstant("z~ynxx!H%\"");
        String string0 = dorisPivotedQuerySynthesisOracle0.getExpectedValues(dorisConstant0);
        assertNotNull(string0);
    }

    @Test
    public void test2() throws Throwable {
        DorisPivotedQuerySynthesisOracle dorisPivotedQuerySynthesisOracle0 = new DorisPivotedQuerySynthesisOracle(
                (DorisProvider.DorisGlobalState) null);
        try {
            dorisPivotedQuerySynthesisOracle0.getRectifiedQuery();
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("sqlancer.doris.oracle.DorisPivotedQuerySynthesisOracle", e);
        }
    }

    @Test
    public void test3() throws Throwable {
        DorisProvider.DorisGlobalState dorisProvider_DorisGlobalState0 = new DorisProvider.DorisGlobalState();
        DorisPivotedQuerySynthesisOracle dorisPivotedQuerySynthesisOracle0 = new DorisPivotedQuerySynthesisOracle(
                dorisProvider_DorisGlobalState0);
        // Undeclared exception!
        try {
            dorisPivotedQuerySynthesisOracle0.getRectifiedQuery();
            fail("Expecting exception: AssertionError");

        } catch (AssertionError e) {
            //
            // null
            //
        }
    }

    @Test
    public void test4() throws Throwable {
        DorisProvider.DorisGlobalState dorisProvider_DorisGlobalState0 = new DorisProvider.DorisGlobalState();
        DorisPivotedQuerySynthesisOracle dorisPivotedQuerySynthesisOracle0 = new DorisPivotedQuerySynthesisOracle(
                dorisProvider_DorisGlobalState0);
        DorisSelect dorisSelect0 = new DorisSelect();
        // Undeclared exception!
        try {
            dorisPivotedQuerySynthesisOracle0.getExpectedValues(dorisSelect0);
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("sqlancer.doris.visitor.DorisToStringVisitor", e);
        }
    }

    private void verifyException(String s, Exception e) {
    }

    @Test
    public void test5() throws Throwable {
        DorisPivotedQuerySynthesisOracle dorisPivotedQuerySynthesisOracle0 = new DorisPivotedQuerySynthesisOracle(
                (DorisProvider.DorisGlobalState) null);
        // Undeclared exception!
        try {
            dorisPivotedQuerySynthesisOracle0.getExpectedValues((DorisExpression) null);
            fail("Expecting exception: AssertionError");

        } catch (AssertionError e) {
            //
            // null
            //
        }
    }

    @Test
    public void test6() throws Throwable {
        DorisPivotedQuerySynthesisOracle dorisPivotedQuerySynthesisOracle0 = new DorisPivotedQuerySynthesisOracle(
                (DorisProvider.DorisGlobalState) null);
        DorisSelect dorisSelect0 = new DorisSelect();
        DorisAlias dorisAlias0 = new DorisAlias(dorisSelect0, "!Z6NDx02%o");
        // Undeclared exception!
        try {
            dorisPivotedQuerySynthesisOracle0.getExpectedValues(dorisAlias0);
            fail("Expecting exception: IllegalStateException");

        } catch (IllegalStateException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("sqlancer.common.ast.SelectBase", e);
        }
    }
}
