/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Apr 07 13:32:02 GMT 2025
 */

package sqlancer.mysql;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class MySQLToStringVisitor_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "sqlancer.mysql.MySQLToStringVisitor"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\yewjo\\OneDrive\\Desktop\\NUS\\y4s2\\cs3213\\project\\sqlancer"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\yewjo\\AppData\\Local\\Temp\\"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(MySQLToStringVisitor_ESTest_scaffolding.class.getClassLoader() ,
      "sqlancer.mysql.ast.MySQLBinaryComparisonOperation",
      "sqlancer.mysql.ast.MySQLColumnReference",
      "sqlancer.mysql.ast.MySQLOrderByTerm$MySQLOrder",
      "sqlancer.mysql.ast.MySQLBinaryLogicalOperation$MySQLBinaryLogicalOperator$1",
      "sqlancer.mysql.ast.MySQLBinaryLogicalOperation$MySQLBinaryLogicalOperator$2",
      "sqlancer.mysql.ast.MySQLBinaryLogicalOperation$MySQLBinaryLogicalOperator$3",
      "sqlancer.mysql.ast.MySQLBinaryLogicalOperation",
      "sqlancer.Randomly$StringGenerationStrategy",
      "sqlancer.common.ast.SelectBase$SelectType",
      "sqlancer.mysql.ast.MySQLBinaryComparisonOperation$BinaryComparisonOperator",
      "sqlancer.mysql.ast.MySQLCastOperation$CastType",
      "sqlancer.mysql.ast.MySQLBinaryLogicalOperation$MySQLBinaryLogicalOperator",
      "sqlancer.common.ast.newast.Join",
      "sqlancer.mysql.ast.MySQLConstant$MySQLNoPQSConstant",
      "sqlancer.common.visitor.ToStringVisitor",
      "sqlancer.mysql.MySQLToStringVisitor",
      "sqlancer.common.schema.AbstractRelationalTable",
      "sqlancer.common.schema.AbstractCastOperation",
      "sqlancer.mysql.MySQLVisitor",
      "sqlancer.common.visitor.NodeVisitor",
      "sqlancer.common.ast.JoinBase",
      "sqlancer.mysql.ast.MySQLComputableFunction$MySQLFunction",
      "sqlancer.mysql.MySQLSchema$MySQLTable",
      "sqlancer.MainOptions",
      "sqlancer.mysql.ast.MySQLInOperation",
      "sqlancer.mysql.ast.MySQLExpression",
      "sqlancer.common.schema.AbstractTableColumn",
      "sqlancer.common.ast.newast.Expression",
      "sqlancer.mysql.ast.MySQLAggregate",
      "sqlancer.mysql.ast.MySQLBinaryOperation$MySQLBinaryOperator",
      "sqlancer.mysql.ast.MySQLSelect$SelectType",
      "sqlancer.mysql.MySQLGlobalState",
      "sqlancer.common.schema.AbstractBinaryLogicalOperation",
      "sqlancer.mysql.MySQLSchema$MySQLDataType",
      "sqlancer.mysql.MySQLSchema$MySQLTable$MySQLEngine",
      "sqlancer.mysql.MySQLSchema$MySQLRowValue",
      "sqlancer.common.schema.TableIndex",
      "sqlancer.mysql.ast.MySQLConstant$MySQLNullConstant",
      "sqlancer.common.schema.AbstractPostfixOperation",
      "sqlancer.mysql.ast.MySQLConstant",
      "sqlancer.mysql.MySQLSchema$MySQLIndex",
      "sqlancer.common.schema.AbstractInOperation",
      "sqlancer.mysql.ast.MySQLConstant$MySQLDoubleConstant",
      "sqlancer.mysql.ast.MySQLConstant$MySQLTextConstant",
      "sqlancer.common.visitor.UnaryOperation",
      "sqlancer.mysql.ast.MySQLBetweenOperation",
      "sqlancer.common.schema.AbstractTable",
      "sqlancer.common.ast.UnaryNode",
      "sqlancer.mysql.ast.MySQLOrderByTerm",
      "sqlancer.GlobalState",
      "sqlancer.common.ast.newast.Select",
      "sqlancer.mysql.ast.MySQLSelect",
      "sqlancer.common.schema.AbstractSchema",
      "sqlancer.mysql.ast.MySQLComputableFunction$MySQLFunction$5",
      "sqlancer.mysql.ast.MySQLComputableFunction$MySQLFunction$6",
      "sqlancer.mysql.ast.MySQLComputableFunction$MySQLFunction$3",
      "sqlancer.mysql.ast.MySQLComputableFunction$MySQLFunction$4",
      "sqlancer.mysql.ast.MySQLComputableFunction$MySQLFunction$1",
      "sqlancer.mysql.ast.MySQLComputableFunction$MySQLFunction$2",
      "sqlancer.mysql.ast.MySQLStringExpression",
      "sqlancer.mysql.ast.MySQLTableReference",
      "sqlancer.mysql.MySQLSchema$MySQLColumn",
      "sqlancer.mysql.ast.MySQLExists",
      "sqlancer.mysql.ast.MySQLBinaryComparisonOperation$BinaryComparisonOperator$1",
      "sqlancer.Randomly",
      "sqlancer.mysql.ast.MySQLBinaryComparisonOperation$BinaryComparisonOperator$3",
      "sqlancer.mysql.ast.MySQLBinaryComparisonOperation$BinaryComparisonOperator$2",
      "sqlancer.mysql.ast.MySQLBinaryComparisonOperation$BinaryComparisonOperator$5",
      "sqlancer.mysql.ast.MySQLBinaryComparisonOperation$BinaryComparisonOperator$4",
      "sqlancer.mysql.ast.MySQLBinaryComparisonOperation$BinaryComparisonOperator$7",
      "sqlancer.mysql.ast.MySQLBinaryComparisonOperation$BinaryComparisonOperator$6",
      "sqlancer.mysql.ast.MySQLCollate",
      "sqlancer.common.visitor.BinaryOperation",
      "sqlancer.mysql.ast.MySQLConstant$MySQLIntConstant",
      "sqlancer.common.ast.JoinBase$JoinType",
      "sqlancer.SQLGlobalState",
      "sqlancer.Randomly$StringGenerationStrategy$4",
      "sqlancer.Randomly$StringGenerationStrategy$3",
      "sqlancer.Randomly$StringGenerationStrategy$2",
      "sqlancer.Randomly$StringGenerationStrategy$1",
      "sqlancer.mysql.ast.MySQLBinaryOperation",
      "sqlancer.mysql.ast.MySQLUnaryPostfixOperation$UnaryPostfixOperator",
      "sqlancer.mysql.ast.MySQLText",
      "sqlancer.mysql.MySQLSchema",
      "sqlancer.mysql.ast.MySQLCastOperation",
      "sqlancer.mysql.ast.MySQLComputableFunction",
      "sqlancer.mysql.ast.MySQLJoin",
      "sqlancer.common.visitor.UnaryOperation$OperatorKind",
      "sqlancer.IgnoreMeException",
      "sqlancer.common.ast.SelectBase",
      "sqlancer.common.schema.AbstractRowValue",
      "sqlancer.mysql.ast.MySQLUnaryPostfixOperation",
      "sqlancer.mysql.ast.MySQLAggregate$MySQLAggregateFunction",
      "sqlancer.mysql.ast.MySQLBinaryOperation$MySQLBinaryOperator$1",
      "sqlancer.mysql.ast.MySQLBinaryOperation$MySQLBinaryOperator$3",
      "sqlancer.common.schema.AbstractCompoundDataType",
      "sqlancer.mysql.ast.MySQLBinaryOperation$MySQLBinaryOperator$2"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(MySQLToStringVisitor_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "sqlancer.common.visitor.NodeVisitor",
      "sqlancer.common.visitor.ToStringVisitor",
      "sqlancer.mysql.MySQLToStringVisitor",
      "sqlancer.mysql.ast.MySQLSelect$SelectType",
      "sqlancer.Randomly$StringGenerationStrategy$4",
      "sqlancer.Randomly$StringGenerationStrategy",
      "sqlancer.Randomly",
      "sqlancer.mysql.ast.MySQLOrderByTerm$MySQLOrder",
      "sqlancer.mysql.ast.MySQLConstant",
      "sqlancer.mysql.ast.MySQLConstant$MySQLNoPQSConstant",
      "sqlancer.mysql.ast.MySQLConstant$MySQLDoubleConstant",
      "sqlancer.mysql.ast.MySQLConstant$MySQLTextConstant",
      "sqlancer.common.schema.AbstractTableColumn",
      "sqlancer.mysql.MySQLSchema$MySQLColumn",
      "sqlancer.mysql.ast.MySQLConstant$MySQLNullConstant",
      "sqlancer.mysql.ast.MySQLConstant$MySQLIntConstant",
      "sqlancer.mysql.ast.MySQLColumnReference",
      "sqlancer.mysql.ast.MySQLExists",
      "sqlancer.common.ast.SelectBase",
      "sqlancer.mysql.ast.MySQLSelect",
      "sqlancer.mysql.ast.MySQLText",
      "sqlancer.mysql.ast.MySQLComputableFunction",
      "sqlancer.mysql.ast.MySQLStringExpression",
      "sqlancer.mysql.ast.MySQLOrderByTerm",
      "sqlancer.mysql.ast.MySQLBetweenOperation",
      "sqlancer.mysql.ast.MySQLAggregate",
      "sqlancer.common.schema.TableIndex",
      "sqlancer.mysql.MySQLSchema$MySQLIndex",
      "sqlancer.common.schema.AbstractTable",
      "sqlancer.common.schema.AbstractRelationalTable",
      "sqlancer.mysql.MySQLSchema$MySQLTable",
      "sqlancer.common.ast.JoinBase",
      "sqlancer.mysql.ast.MySQLJoin",
      "sqlancer.mysql.ast.MySQLBinaryLogicalOperation",
      "sqlancer.mysql.ast.MySQLBinaryComparisonOperation",
      "sqlancer.mysql.ast.MySQLCastOperation",
      "sqlancer.common.ast.UnaryNode",
      "sqlancer.mysql.ast.MySQLCollate",
      "sqlancer.LikeImplementationHelper",
      "sqlancer.mysql.ast.MySQLBinaryOperation",
      "sqlancer.IgnoreMeException",
      "sqlancer.mysql.ast.MySQLInOperation",
      "sqlancer.mysql.ast.MySQLUnaryPostfixOperation",
      "sqlancer.SQLConstantUtils",
      "sqlancer.SQLConstantUtils$CastType",
      "sqlancer.common.ast.UnaryOperatorNode",
      "sqlancer.mysql.ast.MySQLUnaryPrefixOperation",
      "sqlancer.common.visitor.UnaryOperation$OperatorKind",
      "sqlancer.mysql.ast.MySQLTableReference",
      "sqlancer.mysql.MySQLExpectedValueVisitor",
      "sqlancer.GlobalState",
      "sqlancer.SQLGlobalState",
      "sqlancer.mysql.MySQLGlobalState",
      "sqlancer.common.query.Query",
      "sqlancer.common.query.SQLQueryAdapter",
      "sqlancer.common.query.ExpectedErrors",
      "sqlancer.oceanbase.ast.OceanBaseSelect",
      "sqlancer.oceanbase.ast.OceanBaseSelect$SelectType",
      "sqlancer.ExpandedGlobalState",
      "sqlancer.postgres.PostgresGlobalState",
      "sqlancer.citus.CitusGlobalState",
      "sqlancer.hsqldb.HSQLDBSchema$HSQLDBTable",
      "sqlancer.hsqldb.HSQLDBSchema$HSQLDBCompositeDataType",
      "sqlancer.hsqldb.HSQLDBSchema$HSQLDBColumn",
      "sqlancer.common.ast.SelectBase$SelectType"
    );
  }
}
