/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 07 14:16:20 GMT 2025
 */

package sqlancer.evosuite.hsqldb;

import static org.junit.jupiter.api.Assertions.fail;

import org.junit.jupiter.api.Test;

import sqlancer.hsqldb.HSQLDBOptions;

public class HSQLDBOptions_ESTest {

    @Test
    public void test0() throws Throwable {
        HSQLDBOptions hSQLDBOptions0 = null;
        try {
            hSQLDBOptions0 = new HSQLDBOptions();
            fail("Expecting exception: NoSuchMethodError");

        } catch (NoSuchMethodError e) {
            //
            // java.util.List.of(Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/List;
            //
            verifyException("sqlancer.hsqldb.HSQLDBOptions", e);
        }
    }

    private void verifyException(String s, NoSuchMethodError e) {
    }
}
